{
  "hash": "1560bb7a6a48e3d648709e6bc8af28d5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Car Accidents Analysis\"\n---\n\n\n\n\n\n\n# Q1: Car accident dataset\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Q1.1\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Glimpse at the data\nglimpse(accident_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,644\nColumns: 29\n$ X                              <chr> \"DATE\", \"1/01/2016\", \"2/01/2016\", \"3/01…\n$ EASTERN.REGION                 <chr> \"FATAL\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", …\n$ X.1                            <chr> \"SERIOUS\", \"1\", \"3\", \"1\", \"2\", \"1\", \"2\"…\n$ X.2                            <chr> \"NOINJURY\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n$ X.3                            <chr> \"OTHER\", \"5\", \"1\", \"5\", \"2\", \"6\", \"1\", …\n$ METROPOLITAN.NORTH.WEST.REGION <chr> \"FATAL\", \"0\", \"0\", \"0\", \"0\", \"1\", \"0\", …\n$ X.4                            <chr> \"SERIOUS\", \"7\", \"2\", \"3\", \"2\", \"2\", \"5\"…\n$ X.5                            <chr> \"NOINJURY\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n$ X.6                            <chr> \"OTHER\", \"7\", \"4\", \"6\", \"5\", \"7\", \"13\",…\n$ METROPOLITAN.SOUTH.EAST.REGION <chr> \"FATAL\", \"1\", \"0\", \"0\", \"0\", \"0\", \"0\", …\n$ X.7                            <chr> \"SERIOUS\", \"9\", \"8\", \"7\", \"4\", \"6\", \"7\"…\n$ X.8                            <chr> \"NOINJURY\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n$ X.9                            <chr> \"OTHER\", \"3\", \"5\", \"4\", \"5\", \"7\", \"8\", …\n$ NORTH.EASTERN.REGION           <chr> \"FATAL\", \"0\", \"1\", \"0\", \"0\", \"0\", \"0\", …\n$ X.10                           <chr> \"SERIOUS\", \"3\", \"2\", \"2\", \"1\", \"6\", \"0\"…\n$ X.11                           <chr> \"NOINJURY\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n$ X.12                           <chr> \"OTHER\", \"2\", \"1\", \"3\", \"1\", \"2\", \"0\", …\n$ NORTHERN.REGION                <chr> \"FATAL\", \"0\", \"0\", \"0\", \"1\", \"0\", \"0\", …\n$ X.13                           <chr> \"SERIOUS\", \"1\", \"2\", \"0\", \"4\", \"0\", \"3\"…\n$ X.14                           <chr> \"NOINJURY\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n$ X.15                           <chr> \"OTHER\", \"1\", \"1\", \"3\", \"3\", \"3\", \"4\", …\n$ SOUTH.WESTERN.REGION           <chr> \"FATAL\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", …\n$ X.16                           <chr> \"SERIOUS\", \"2\", \"2\", \"2\", \"1\", \"3\", \"1\"…\n$ X.17                           <chr> \"NOINJURY\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n$ X.18                           <chr> \"OTHER\", \"0\", \"2\", \"1\", \"3\", \"1\", \"3\", …\n$ WESTERN.REGION                 <chr> \"FATAL\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0\", …\n$ X.19                           <chr> \"SERIOUS\", \"1\", \"1\", \"2\", \"0\", \"2\", \"2\"…\n$ X.20                           <chr> \"NOINJURY\", \"0\", \"0\", \"0\", \"0\", \"0\", \"0…\n$ X.21                           <chr> \"OTHER\", \"0\", \"2\", \"4\", \"1\", \"1\", \"1\", …\n```\n\n\n:::\n\n```{.r .cell-code}\n# Inspect the size of the dataset\n# Get the dimensions of the dataset\ndims = dim(accident_data)\nobs = dims[1]\nvars = dims[2]\n\n# Print the values\ncat(\"Number of observations:\", obs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of observations: 1644 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of variables:\", vars, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of variables: 29 \n```\n\n\n:::\n:::\n\n### Answer\nIn the data there are 29 columns and 1644 rows, but 1643 of these are observations due to the first row containing header information.\n\n\n## Q1.2\n### Answer\nBased on the data type selection tree, there are four data types in the data. \n\n1. Metric Continuous: Dates.\n   a. Metric: Dates involve units of measurement (like time intervals), which makes them metric.\n   b. Continuous: Dates can be placed on a number line and have meaningful intervals (e.g., the difference between two dates can be measured in days, months, or years).\n2. Metric Discrete: Accident counts.\n   a. Metric: Accident counts can be put on a number line (e.g. 0, 1, 2 accidents) and it has units (accidents).\n   b. Discrete: The accident count doesn't come from measuring, it comes from counting.\n   \n3. Categorical Nominal: Region names.\n   a. Categorical: The region names cannot be put on a number line.\n   b. Nominal: There is no meaningful order to the names of the regions. \n\n4. Categorical Ordinal: Accident types.\n   a. Categorical: The type of accident cannot be put on a number line.\n   b. Ordinal: We can put the accident types into a meaningful order based on severity, e.g. OTHER, NOINJURY, SERIOUS, FATAL.\n\n\n## Q1.3\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Count the number of regions in the data by selecting only columns containing the word\n# REGION and then get the number of columns from this selection. \n# Filter columns with \"REGION\" in their names\nregions = accident_data |> \n  dplyr::select(contains(\"REGION\"))\n\n# Get the number of columns in the slected data\nnum_regions = dim(regions)[2]\n\n# Print the values\ncat(\"Number of regions:\", num_regions, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of regions: 7 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# The data imports with two rows for the header and the Date values are in the first\n# column called X.\n# I just need to get the values from the 2nd to the last row in the first column.\n\n# Extract the date values starting from the second row\ndate_values = accident_data$X[2:nrow(accident_data)]\n\n# Convert to Date format (day/month/year)\ndate_values = dmy(date_values)\n\n# Get the date range\ndate_range = range(date_values, na.rm = TRUE)\n\n# Print the result\nprint(date_range)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2016-01-01\" \"2020-06-30\"\n```\n\n\n:::\n:::\n\n\n### Answer\n* The number of regions in the data is 7.\n* The time period covered by the data is from January 1st 2016 to June 30th 2020. \n\n\n## Q1.4\n### Answer\nThe variable FATAL represents accident that result in death. It is a count of how many people died in each region on a given date in car accidents. The variable SERIOUS represents accidents that result in serious injuries, but not death. It is a count of how many people were seriously injured in each region on a given date in car accidents. The difference between the variables is death. They both count car accidents, but FATAL records if death occurred. Visual inspection of the data shows the there are more SERIOUS accidents than FATAL. \n\n\\newpage\n# Q2: Tidy data\n## Q2.1\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# This code was provided with the question\ncav_data_link <- 'car_accidents_victoria.csv' \ntop_row <- read_csv(cav_data_link, col_names = FALSE, n_max = 1) \nsecond_row <- read_csv(cav_data_link, n_max = 1) \n \ncolumn_names <- second_row %>%  \n  unlist(., use.names=FALSE) %>%  \n  make.unique(., sep = \"__\") # double underscore \n \ncolumn_names[2:5] <- str_c(column_names[2:5], '0', sep='__') \n \ndaily_accidents <-  \n  read_csv(cav_data_link, skip = 2, col_names = column_names)\n```\n:::\n\n\n### Answer\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Use top row to extract the region names\nregion_names = top_row |>\n  dplyr::select(-X1) |> \n  unlist(use.names = FALSE) |> \n  discard(~ .x == \"\" | is.na(.x)) |> \n  unique()\n\nprint(region_names)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"EASTERN REGION\"                 \"METROPOLITAN NORTH WEST REGION\"\n[3] \"METROPOLITAN SOUTH EAST REGION\" \"NORTH EASTERN REGION\"          \n[5] \"NORTHERN REGION\"                \"SOUTH WESTERN REGION\"          \n[7] \"WESTERN REGION\"                \n```\n\n\n:::\n:::\n\n\n\n## Q2.2\n### Answer\n#### a.\n* Does each variable have its own column? No. Apart from the DATE column, all other columns are combinations of two variables, the accident type (FATAL, SERIOUS, NOINJURY, OTHER) and the region (as a number).\n\n* Does each observation have its own row? No. Each row is a date plus results (counts) for combinations of region and accident types. A single observation per row would be one date, one region, one accident type and the count.\n\n* Does each value have its own cell? Yes. The number of accidents (count) is in its own cell.\n\n\n#### b.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Pivot to long format\ntidy_accidents = daily_accidents |>\n  pivot_longer(\n    cols = -DATE,\n    names_to = \"var\",\n    values_to = \"accident_count\"\n  )\n\n# Separate accident type and region index\ntidy_accidents = tidy_accidents |> \n  separate(var, into = c(\"accident_type\", \"region_index\"), sep = \"__\") |>\n  mutate(region_index = as.integer(region_index))\n\n# Map region_index to region names using region_names\ntidy_accidents <- tidy_accidents |>\n  mutate(region_name = region_names[region_index + 1]) # +1 because R is 1-based\n```\n:::\n\n\n* How many pivot_wider operation do you need? None, the data is already in wide format.\n\n* How many pivot_longer operations do you need? One.\n\n* Explain the steps in detail.\n  * Step 1: Gather all columns except DATE into two columns called \"var\" and \"accident_count\". Column \"var\" contains the original column names which is a combination of accident type and region. The \"accident_count\" columns contains the values from the original columns (i.e. the number of accidents).   \n  \n  * Step 2: Separate the values in the \"var\" column into two columns, \"accident_type\" (type of accident) and \"region_index\" (index of region). The \"region_index\" is converted into integers using the mutate function.\n\n  * Step 3: The last step is optional, but it takes the region_index and creates a column for the \"region_name\" by indexing the region_names list create in Q2.1.\n\n* Provide/print the head of the dataset.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(tidy_accidents)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  DATE      accident_type region_index accident_count region_name               \n  <chr>     <chr>                <int>          <dbl> <chr>                     \n1 1/01/2016 FATAL                    0              0 EASTERN REGION            \n2 1/01/2016 SERIOUS                  0              1 EASTERN REGION            \n3 1/01/2016 NOINJURY                 0              0 EASTERN REGION            \n4 1/01/2016 OTHER                    0              5 EASTERN REGION            \n5 1/01/2016 FATAL                    1              0 METROPOLITAN NORTH WEST R…\n6 1/01/2016 SERIOUS                  1              7 METROPOLITAN NORTH WEST R…\n```\n\n\n:::\n:::\n\n\n\n#### c.\n* Are the variables having the expected variable types in R?\nNo, not all variables have the expected type. The \"DATE\" columns needs to be converted to a Date, the \"accident_type\" column should be an ordered factor, \"accident_count\" should be an integer and region_name should be a factor.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy_accidents = tidy_accidents |>\n  mutate(DATE = dmy(DATE))  |> \n  mutate(\n    accident_type = ordered(accident_type,levels = c(\"OTHER\", \"NOINJURY\",\n                                                     \"SERIOUS\", \"FATAL\"))\n    ) |> \n  mutate(accident_count = as.integer(accident_count)) |> \n  mutate(region_name = as.factor(region_name))\n\nhead(tidy_accidents)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  DATE       accident_type region_index accident_count region_name              \n  <date>     <ord>                <int>          <int> <fct>                    \n1 2016-01-01 FATAL                    0              0 EASTERN REGION           \n2 2016-01-01 SERIOUS                  0              1 EASTERN REGION           \n3 2016-01-01 NOINJURY                 0              0 EASTERN REGION           \n4 2016-01-01 OTHER                    0              5 EASTERN REGION           \n5 2016-01-01 FATAL                    1              0 METROPOLITAN NORTH WEST …\n6 2016-01-01 SERIOUS                  1              7 METROPOLITAN NORTH WEST …\n```\n\n\n:::\n:::\n\n\n\n#### d.\n* Are there any missing values? Yes, there are 4 missing values in the accident_count column.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Number of missing observations per column:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of missing observations per column:\n```\n\n\n:::\n\n```{.r .cell-code}\n# Count missing values per column\ncolSums(is.na(tidy_accidents))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          DATE  accident_type   region_index accident_count    region_name \n             0              0              0              4              0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Get some summary statistics\nsummary(tidy_accidents)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      DATE             accident_type    region_index accident_count \n Min.   :2016-01-01   OTHER   :11501   Min.   :0     Min.   : 0.00  \n 1st Qu.:2017-02-14   NOINJURY:11501   1st Qu.:1     1st Qu.: 0.00  \n Median :2018-04-01   SERIOUS :11501   Median :3     Median : 0.00  \n Mean   :2018-04-01   FATAL   :11501   Mean   :3     Mean   : 1.44  \n 3rd Qu.:2019-05-17                    3rd Qu.:5     3rd Qu.: 1.00  \n Max.   :2020-06-30                    Max.   :6     Max.   :33.00  \n                                                     NA's   :4      \n                         region_name  \n EASTERN REGION                :6572  \n METROPOLITAN NORTH WEST REGION:6572  \n METROPOLITAN SOUTH EAST REGION:6572  \n NORTH EASTERN REGION          :6572  \n NORTHERN REGION               :6572  \n SOUTH WESTERN REGION          :6572  \n WESTERN REGION                :6572  \n```\n\n\n:::\n:::\n\n\n*  From the summary data above you can see the median in the accident_count is 0, the mean is 1.44 and the maximum accident_count is 33. The mean is higher than the median, potentially due to outliers. Therefore, I will use the median value to impute the missing counts as it is robust against outliers, it also retains the data being an integer type. Whilst, the crash data is also a time series I do not believe a froward fill or backward fill is appropriate here. The number of accident yesterday to tomorrow are unlikely to be related to today.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fix missing data in the count column using the median.\ntidy_accidents <- tidy_accidents |>\n  mutate(accident_count = if_else(is.na(accident_count),\n                                  median(accident_count, na.rm = TRUE), accident_count))\n\n# Check the missing count is now zero in all columns.\ncolSums(is.na(tidy_accidents))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          DATE  accident_type   region_index accident_count    region_name \n             0              0              0              0              0 \n```\n\n\n:::\n:::\n\n\n\\newpage\n# Q3: Fitting distributions\nFor this question I need to create the \"TOTAL_ACCIDENTS\" data. As confirmed by the unit chair (22/9/25) this is the total number of accidents for each day in the dataset.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Group and summarise the accident_count by date\ntotal_accidents = tidy_accidents |> \n  group_by(DATE) |> \n  summarise(count = sum(accident_count), .groups = \"drop\")\n```\n:::\n\n\n\n## Q3.1\n### Answer\n\n### Poisson distribution\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# get total count\ntotal_count = total_accidents$count\n\n# Fitting a Poisson distribution\nfit_pois = fitdist(total_count, \"pois\")\n\n# View summary\nsummary(fit_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFitting of the distribution ' pois ' by maximum likelihood \nParameters : \n       estimate Std. Error\nlambda 40.32806  0.1566696\nLoglikelihood:  -6565.159   AIC:  13132.32   BIC:  13137.72 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot diagnostic graphs\nplot(fit_pois)\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=576}\n:::\n:::\n\n### Negative binomial distribution\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fitting a negative binomial distribution\nfit_nb = fitdist(total_count, \"nbinom\")\n\n# View summary\nsummary(fit_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFitting of the distribution ' nbinom ' by maximum likelihood \nParameters : \n     estimate Std. Error\nsize 26.89578  1.5909547\nmu   40.32640  0.2476714\nLoglikelihood:  -6110.248   AIC:  12224.5   BIC:  12235.3 \nCorrelation matrix:\n             size           mu\nsize 1.0000000000 0.0002372614\nmu   0.0002372614 1.0000000000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot diagnostic graphs\nplot(fit_nb)\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n## Q3.2\n### Answer\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create a summary table\ndistribution_lik_comparison = tibble(\n  Model = c(\"Poisson\", \"Negative Binomial\"),\n  LogLikelihood = c(fit_pois$loglik, fit_nb$loglik)\n)\nprint(distribution_lik_comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  Model             LogLikelihood\n  <chr>                     <dbl>\n1 Poisson                  -6565.\n2 Negative Binomial        -6110.\n```\n\n\n:::\n:::\n\nFrom the above log-likelihood values, the negative Binomial distribution has the higher (least negative) value, which means it fits the data better than the Poisson distribution, this is supported with the density plots produced for each distribution. This suggest that the accident count data likely exhibits over-dispersion (the variance is greater than the mean) as the negative Binomial distribution can handle data that exhibits over-dispersion. For a Poisson distribution, the variance is equal to the mean, making it harder to fit data with over-dispersion.\n\n\n## Q3.3\n### Answer\nThis question requires the total counts across regions grouped by accident type. It also requires the addition of a third distribution to assess. Although the data is discrete, I included the Normal distribution to explore how a continuous model might capture the overall shape and spread of accident counts, especially since other discrete alternatives like the Geometric distribution did not reflect the characteristics of the data well.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Group and summarise the accident_count by date and accident type\ntotal_accidents_by_type = tidy_accidents |> \n  group_by(DATE, accident_type) |> \n  summarise(count = sum(accident_count), .groups = \"drop\")\n\n# Filter for SERIOUS accident types\nserious_accidents = total_accidents_by_type |>\n  filter(accident_type == \"SERIOUS\")\n\nserious_counts = serious_accidents$count\n\n# Filter for FATAL accident types\nfatal_accidents = total_accidents_by_type |>\n  filter(accident_type == \"FATAL\")\n\nfatal_counts = fatal_accidents$count\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fitting distributions to the SERIOUS data\nfit_nb_ser = fitdist(serious_counts, \"nbinom\")\nfit_pois_ser = fitdist(serious_counts, \"pois\")\nfit_norm_ser = fitdist(serious_counts, \"norm\")\n\n# Fitting distributions to the FATAL data\nfit_nb_fat = fitdist(fatal_counts, \"nbinom\")\nfit_pois_fat = fitdist(fatal_counts, \"pois\")\nfit_norm_fat = fitdist(fatal_counts, \"norm\")\n\n# Create a DataFrame manually with log-likelihoods\nresults_table_3_3 = data.frame(\n  Distribution_name = c(\"Poisson\", \"Negative Binomial\", \"Normal\",\n                        \"Poisson\", \"Negative Binomial\", \"Normal\"),\n  Accident_type = c(\"SERIOUS\", \"SERIOUS\", \"SERIOUS\",\n                    \"FATAL\", \"FATAL\", \"FATAL\"),\n  Log_likelihood = c(\n    fit_pois_ser$loglik,\n    fit_nb_ser$loglik,\n    fit_norm_ser$loglik,\n    fit_pois_fat$loglik,\n    fit_nb_fat$loglik,\n    fit_norm_fat$loglik\n  )\n)\n\nprint(results_table_3_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Distribution_name Accident_type Log_likelihood\n1           Poisson       SERIOUS      -6225.577\n2 Negative Binomial       SERIOUS      -5464.884\n3            Normal       SERIOUS      -5356.787\n4           Poisson         FATAL      -2010.458\n5 Negative Binomial         FATAL      -2009.523\n6            Normal         FATAL      -2242.277\n```\n\n\n:::\n:::\n\n\nI fitted three distributions, Poisson, Negative Binomial, and Normal to the TOTAL_ACCIDENTS data for SERIOUS and FATAL accident types. The goal was to assess which distribution best models the data by comparing their log-likelihood values.\n\nFor **SERIOUS** accidents, the Normal distribution had the highest log-likelihood (-5356.787), followed by the Negative Binomial (-5464.884), and then Poisson (-6225.577). This suggests that the Normal distribution may better capture the central tendency and spread of the data. \nHowever, since accident counts in accidents are discrete, the Negative Binomial is a better choice, although it yields a slightly lower log-likelihood.\n\nFor **FATAL** accidents, the best result was offered by the Negative Binomial (-2009.523), just edging out the Poisson (-2010.458), and the Normal lagged behind (-2242.277). This indicates that the Negative Binomial effectively models the over-dispersion and variability in fatal accident counts.\n\nOverall, the Negative Binomial distribution consistently provides a strong fit across both accident types, striking a balance between statistical performance and suitability for discrete count data. The Normal distribution may be useful in exploratory analysis, but is less appropriate for modelling count-based outcomes.\n\n\\newpage\n# Q4: Source weather data\nTo answer questions 4 and 5, I need to select a region. The unit chair confirmed this via email on 22/9/25. I have used the answer to question 7.1, which is the \"METROPOLITAN SOUTH EAST REGION\".\n\n\n## Q4.1\n### Answer\nFor my data source I selected the NOAA Climate data because it was freely available, accessible from within R, has the data range I required, has the variables (temperature and precipitation) I require and comes in a form the is easy to work with within R.\n\n\n## Q4.2\n### Answer\nFor the weather station I have chosen Moorabbin airport as it is within the region of interest.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set some options\nstation_id = \"ASN00086077\"  # MOORABBIN AIRPORT \nstart_date = \"2015-12-02\" # 30 days before the start of the accident data. Helps with Q5\nend_date   = \"2020-07-02\" # 2 days after the accident data. Helps with Q5 \n\n# Download data\nnoaa_data = ghcnd_search(stationid = station_id,\n                         date_min = start_date, date_max = end_date)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Combine tmin and tmax to get average temperature\n# Merge tmin and tmax by date\ntemps = merge(noaa_data$tmin, noaa_data$tmax, by = \"date\", suffixes = c(\"_min\", \"_max\"))\n\n# Count missing values per column\ncat(\"Number of missing observations in temperature:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of missing observations in temperature:\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(temps))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     date    id_min      tmin mflag_min qflag_min sflag_min    id_max      tmax \n        0         0         1         0         0         0         0         0 \nmflag_max qflag_max sflag_max \n        0         0         0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Forward fill missing values for average temperature and precipitation.\n# Here I have assumed that today's temperature a good approximation for tomorrow.\ntemps$tmin = na.locf(temps$tmin) \n\n# Calculate average temperature (in tenths of degrees C, so divide by 10)\ntemps = temps |>\n  mutate(\n    tavg = (tmin + tmax) / 2 / 10\n  )\ntemps$tmin = temps$tmin / 10\ntemps$tmax = temps$tmax / 10\n\n# Precipitation (in in tenths of millimeter, so divided by 10)\nprcp = noaa_data$prcp\nprcp$prcp = prcp$prcp / 10\n\n# Count missing values per column\ncat(\"\\nNumber of missing observations in precipitation:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNumber of missing observations in precipitation:\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(prcp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id  prcp  date mflag qflag sflag \n    0     3     0     0     0     0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Forward fill missing values for precipitation.\n# Similar to temperature, I have assumed today's rainfall is a good approximation for\n# tomorrow.\nprcp$prcp = na.locf(prcp$prcp)\n\n# Merge temperature and precipitation by date\nweather_data = merge(temps[, c(\"date\", \"tmin\", \"tmax\", \"tavg\")],\n                     prcp[, c(\"date\", \"prcp\")], by = \"date\", all = TRUE)\n\n# Count missing values per column\ncat(\"\\nNumber of missing weather observations:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNumber of missing weather observations:\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(weather_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndate tmin tmax tavg prcp \n   0    0    0    0    0 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather_data |>  \n  ggplot(aes(x=date, \n             y=tavg)) + \n  geom_line(color='darkgreen') + \n  labs(\n    title =  expression(\"Average Daily Temperature (\" * degree * \"C\" * \")\"),\n    x = \"Date\",\n    y = expression(\"Average Temperature (\" * degree * \"C\" * \")\")\n  ) +\n  theme(plot.title=element_text(hjust=0.5))\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather_data |>  \n  ggplot(aes(x=date, \n             y=prcp)) + \n  geom_line(color='blue') + \n  labs(\n    title = \"Daily Precipitation (mm)\",\n    x = \"Date\",\n    y = \"Precipitation (mm)\"\n  ) +\n  theme(plot.title=element_text(hjust=0.5))\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n## Q4.3\n### Answer\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Get the dimensions of the dataset\ndims = dim(weather_data)\nobs = dims[1]\nvars = dims[2]\n\n# Print the values\ncat(\"Number of observations:\", obs, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of observations: 1675 \n```\n\n\n:::\n:::\n\n* There are 1675 rows in the local weather data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Get the date range\nweather_date_range = range(weather_data$date, na.rm = TRUE)\n\n# Print the result\nprint(weather_date_range)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2015-12-02\" \"2020-07-02\"\n```\n\n\n:::\n:::\n\n* The data covers the time period from December 12th 2015 to July 2nd 2020. This date range has been extend before and after the accident data range to accommodate rolling averages required in the answer to Question 5. \n\n\\newpage\n# Q5: Heatwaves, preciptation and road accidents\n## Q5.1\n### Answer\nThe paper \"The Excess Heat Factor: A Metric for Heatwave Intensity and Its Use in Classifying Heatwave Severity\" by John R. Nairn and Robert J. B. Fawcett proposes a new index, the Excess Heat Factor (EHF), for monitoring and forecasting heatwaves in Australia. The EHF is designed to measure heatwave intensity in a way that is relevant to human health outcomes and can be applied consistently across Australia's diverse climates. It achieves this by considering both long-term climate norms and short-term acclimatisation to recent temperatures.\n\nThe EHF is a measure of heatwave intensity calculated over a three-day period (TDP). It is formulated from two separate indices, called Excess Heat Indices (EHIs). The EHIs are the Significance Index (EHIsig) and the Acclimatisation Index (EHIaccl).\n\nThe EHIsig index measures the intensity of TDP relative to the location's long-term climate. It is defined as the three-day-averaged Daily Mean Temperature (DMT) minus the Long-Term Threshold (T95) temperature threshold. A positive EHIsig indicates that the three-day period is unusually warm for that location. DMT is the simple average of the daily maximum and daily minimum temperatures, and T95 is the 95th percentile of the DMT, calculated from a long-term climatological record (e.g., 1971-2000) for a specific location.\n\nThe EHIaccl index measures how the temperature of a three-day period compares to the recent past, accounting for human adaptation. It is defined as the three-day-averaged DMT minus the average DMT of the preceding 30 days. A positive EHIaccl signifies that the three-day period is hotter than the recent past, suggesting a lack of acclimatisation.\n\nThe Excess Heat Factor (EHF) is the product of these two indices, with the condition that the acclimatisation index only amplifies the result if it is greater than 1. A heatwave is considered to be present only when the EHF is positive, which requires the significance index (EHIsig) to be positive.\n\n\n## Q5.2\n### Answer\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate the Excess Heat Factor (EHF)\n\n# Calculate the long-term 95th percentile (T95)\n# The paper uses a 1971-2000 climatology period.\n# Download data date from 1971 to 2000\nnoaa_data_1971_2000 = ghcnd_search(\n  stationid = station_id,\n  date_min = \"1971-01-01\",\n  date_max = \"2000-12-31\"\n)\n\n# Combine tmin and tmax to get average temperature\n# Merge tmin and tmax by date\ntemps_1971_2000 = inner_join(noaa_data_1971_2000$tmin, noaa_data_1971_2000$tmax,\n                             by = \"date\", suffix = c(\"_min\", \"_max\")) |>\n  mutate(tavg = (tmin + tmax) / 2 / 10)\n\n# Calculate the 95% percentile, ignoring and NA's\nt95 = quantile(temps_1971_2000$tavg, probs = 0.95, na.rm = TRUE)\ncat(\"Calculated T95 (95th percentile temperature) is:\", round(t95, 2), \"\\u00B0C\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCalculated T95 (95th percentile temperature) is: 23.2 °C\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate 3-day and 30-day rolling mean temperatures\n# For 3-day DMT I use a 'left' alignment to match the paper's forward-looking formula\n# for a three-day period (TDP) starting on day 'i' (T_i, T_{i+1}, T_{i+2}) page 233.\nweather_data = weather_data |> \n  mutate(\n      # 3-day average DMT\n      dmt_3day_avg = rollmean(tavg, k = 3, fill = NA, align = \"left\"),\n      # 30-day average DMT. Lag the temperature series before applying a \n      # trailing (right-aligned) rolling mean.\n      dmt_30day_past_avg = rollmean(lag(tavg), k = 30, fill = NA, align = \"right\")\n    )\n\n# Calculate the Excess Heat Indices (EHI)\nweather_data = weather_data |> \n    mutate(\n      # Significance Index\n      EHI_sig = dmt_3day_avg - t95,\n      # Acclimatisation Index\n      EHI_accl = dmt_3day_avg - dmt_30day_past_avg\n    )\n\n# Calculate the Excess Heat Factor (EHF)\n# EHF is the product of the two indices.\n# A heatwave is only present if EHF is positive, which requires EHI_sig > 0.\n# Negative EHF values are set to 0 as their magnitude is not interpreted.\nweather_data = weather_data |> \n    mutate(\n      EHF = EHI_sig * pmax(1, EHI_accl),\n      EHF = if_else(EHF < 0, 0, EHF)\n    )\n```\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweather_data |> \n  ggplot(aes(x = date, y = EHF)) +\n  geom_line(color=\"red\", linewidth = 0.8) + \n  labs(\n    title = \"Excess Heat Factor (EHF)\",\n    subtitle = \"Based on the methodology by Nairn and Fawcett (2015)\",\n    x = \"Date\",\n    y = expression(\"Excess Heat Factor (\" * degree * \"C\"^2 * \")\"),\n    linetype = \"Threshold\"\n  )+\n  theme(plot.title=element_text(hjust=0.5), plot.subtitle=element_text(hjust=0.5) )\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\\newpage\n# Q6: Model planning\n## Q6.1\n### Answer\n#### a.\nThe main goal of the model is to predict the daily number of road traffic accidents in a specific region of Victoria. This predictive model will be used for forecasting, enabling proactive resource management and public safety alerts.\n\n#### b.\nThe model is highly relevant, as the number of accidents directly correlates with the demand for emergency services, such as ambulances, police, and fire brigades. Accurate prediction enables staff rostering, tactical deployment of units, and overall preparedness for particularly high-risk days as it relates to specific weather conditions.\n\n#### c.\nPotential users include emergency service planners, traffic management authorities (like VicRoads), public health officials, and government policy makers concerned with road safety.\n\n\n## Q6.2\n### Answer\n#### a.\nThe plan is to model the relationship between various weather conditions (temperature and rainfall) and temporal factors (like day of the week, month) and the number of daily road traffic accidents.\n\n#### b.\nThe response variable ($Y$) is the daily count of road traffic accidents in the selected region.\n\n#### c.\nThe predictor variables will be:\n\n* Weather data: Maximum and minimum temperature and rainfall.\n* Heat-related metric: The Extreme Heat Factor (EHF).\n* Temporal factors: Month as a number.\n\n#### d.\nYes. Weather data is forecast daily and measurements are usually available in real time or lagged by a day so so, making it ideal for predictive modeling. The temporal factors are known in advance. This allows the model to generate future predictions for operational planning. The EHF as formulated by John Nairn and Robert Fawcett needs two days forward of the calculation date, so any values used will also need to be 2 days behind the prediction. \n\n#### e.\nI will assume that the fundamental relationships between weather, driver behaviour, and accident risk will remain relatively stable in the short term. However, it's a limitation to consider, as long-term trends like climate change, changes in vehicle technology, and new road infrastructure could alter these characteristics over a longer period.\n\n## Q6.3\n### Answer\nThe primary statistical methods will be Linear Models (LM) and Generalised Additive Models (GAM).\n\n* Linear Model: This will be used as a baseline model. It is simple to implement and interpret, and will help determine if there are any basic linear relationships between the predictors and the accident count.\n\n* Generalised Additive Model (GAM): This method will be used to improve the linear model because it relaxes the strict assumption of linearity. The relationship between weather variables and accidents is likely non-linear. A GAM can model these complex relationships using flexible smooth functions. Furthermore, since the response variable is a count and I have shown in Question 3 that the Negative Binomial distribution is better suited to the data, the GAM can be fitted using this distribution, which is more suitable for count data than the Normal distribution assumed by a standard linear model.\n\n\\newpage\n# Q7: Model the number of road traffic accidents\n\n## Q7.1\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(4)\nselected_region = sample(region_names, 1)\nselected_region\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"METROPOLITAN SOUTH EAST REGION\"\n```\n\n\n:::\n:::\n\n### Answer\nMy randomly selected region is \"METROPOLITAN SOUTH EAST REGION\".\n\n\nFor this question I need to get the predictor variables together into a single DataFrame for this selected region.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_totals = tidy_accidents |> \n  group_by(DATE, region_name) |> \n  summarise(count = sum(accident_count), .groups = \"drop\")\n\n# Filter for the METROPOLITAN SOUTH EAST REGION\ntotal_accidents_mse = region_totals |> \n  filter(region_name == \"METROPOLITAN SOUTH EAST REGION\")\n\ntotal_accidents_mse = total_accidents_mse |> \n  dplyr::select(-region_name)\n\ndata = total_accidents_mse |> \n  mutate(\n    weekday_num = wday(DATE, week_start = 1),  # Monday = 1\n    month_num = month(DATE)                    # January = 1\n  )\n\n# Select only some of the columns from the weather_data\nweather_selected <- weather_data |> \n  dplyr::select(date, tmin, tmax, tavg, prcp, EHF)  \n\n# Merge using left_join to keep only rows from data\n# This trims the weather data back to the same date range as the accidents\nmerged_df = data |> \n  left_join(weather_selected, by = c(\"DATE\" = \"date\"))\n```\n:::\n\n\n## Q7.2\n### Answer\nI have interpreted **linear model** to mean linear regression not GLM. I have left the rainfall predictor for question 7.7.\n\n### Linear model\nI fitted a linear model using lm() to predict the number of road traffic accidents (count) using weekday number, month number, maximum temperature (tmax), and minimum temperature (tmin) as predictors.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Model 1: weekday, month, max and min temperature\nlm_model1 <- lm(count ~ weekday_num + month_num + tmax + tmin, data = merged_df)\nmodel1_results = augment(lm_model1)\nsummary(lm_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = count ~ weekday_num + month_num + tmax + tmin, data = merged_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-12.8626  -3.1626  -0.2735   3.0601  19.3361 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 14.18531    0.57039  24.869  < 2e-16 ***\nweekday_num -0.36636    0.05818  -6.297 3.89e-10 ***\nmonth_num    0.08205    0.03562   2.304 0.021371 *  \ntmax         0.09106    0.02356   3.865 0.000116 ***\ntmin        -0.08851    0.03453  -2.563 0.010460 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.716 on 1638 degrees of freedom\nMultiple R-squared:  0.03602,\tAdjusted R-squared:  0.03367 \nF-statistic:  15.3 on 4 and 1638 DF,  p-value: 2.723e-12\n```\n\n\n:::\n:::\n\nThe model summary shows the R-squared value is very low (~3.4%), indicating the linear model explains only a small portion of the variance in the accident counts.\n\n### Plot of fitted versus actuals\nThe model predicts values mostly between 12 and 18, regardless of the actual accident count, suggesting the model is not responsive to variation in the actual data. Actual accident counts vary widely (0 to 30), but the model doesn’t reflect this, indicating under-fitting. The plot does not following the expected diagonal trend (where fitted = actual). Here, the points are scattered horizontally, showing poor predictive accuracy. The fitted values do not closely follow the actual values, and there's considerable scatter, suggesting poor predictive accuracy.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(Actual =model1_results$count, Fitted = model1_results$.fitted),\n       aes(x = Actual, y = Fitted)) +\n  geom_point(alpha = 0.6, color = \"darkgreen\") +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"red\", size = 1.0) +\n  labs(title = \"Actual vs Fitted Values (Linear model) \", x = \"Actual\", y = \"Fitted\") +\n  theme(plot.title=element_text(hjust=0.5))\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n### Plot of residuals versus fitted\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Function for plotting residuals versus fitted\nplot_residuals = function(model) {\n  model_results = augment(model)\n  model_results |> \n    ggplot(aes(.fitted, .resid)) +\n    geom_point(alpha=0.5) +\n    geom_hline(yintercept=0, color=\"red\", linetype=\"dashed\") +\n    geom_quantile() +\n    geom_smooth(colour=\"firebrick\") +\n    labs(title=\"Residuals vs Fitted (Linear model)\", x=\"Fitted Values\", y=\"Residuals\") +\n    theme(plot.title=element_text(hjust=0.5))\n}\n\n# Plot residuals\nplot_residuals(lm_model1)\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Function to help plotting residuals versus feature\nplot_residuals_v_feat = function(model, feature, label, sub_label, model_label) {\n  model_results = augment(model)\n  \n  ggplot(model_results, aes_string(x = feature, y = \".resid\")) +\n    geom_point(alpha = 0.5) +\n    geom_hline(yintercept = 0, color = \"red\", linetype = \"dashed\") +\n    geom_quantile() +\n    geom_smooth(colour = \"firebrick\") +\n    labs(title = paste(\"Residuals vs\", label, model_label), x = paste(label, sub_label),\n         y = \"Residuals\") +\n    theme(plot.title = element_text(hjust = 0.5))\n}\n```\n:::\n\n\n### Residuals vs Weekday number\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = lm_model1, feature = \"weekday_num\", label = \"Weekday\",\n                      sub_label=\" (1=Mon, ..., 7=Sun)\", model_label=\"(Linear model)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n### Residuals vs Month number\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = lm_model1, feature = \"month_num\", label = \"Month\",\n                      sub_label=\" (1=Jan, ..., 12=Dec)\", model_label=\"(Linear model)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=576}\n:::\n:::\n\n### Residuals vs Maximum temperature\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = lm_model1, feature = \"tmax\", label = \"Maximum Temperature\",\n                      sub_label=\"\", model_label = \"(Linear model)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n### Residuals vs Minimum temperature\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = lm_model1, feature = \"tmin\", label = \"Minium Temperature\",\n                      sub_label=\"\", model_label=\"(Linear model)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-37-1.png){fig-align='center' width=576}\n:::\n:::\n\n\nResiduals versus fitted appear randomly scattered but with some spread, indicating that the linear model may not capture non-linear relationships or other structure in the data. Plots of residuals versus features show cyclic patterns for the day of the week and the month.\n\nBased on the low R-squared value, residual patterns, and poor alignment between fitted and actual values, a linear model is insufficient for modeling the trend in accident counts.\n\n\n## Q7.3\n### Answer\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Weekday_num and month_num are cyclic so I have used the cyclic cubic spline \"cc\"\n# and specific the wrap around knots\ngam_nb = gam(\n  count ~ s(weekday_num, bs=\"cc\", k=7) + s(month_num, bs=\"cc\", k=12) + s(tmax) + s(tmin),\n  family=nb(link = \"log\"),\n  data = merged_df,\n  knots = list(weekday_num = c(1, 8),  # wrap from 7 to 1\n               month_num = c(1, 13)    # wrap from 12 to 1\n  ))\ngam_nb_results = augment(gam_nb)\nsummary(gam_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFamily: Negative Binomial(34.53) \nLink function: log \n\nFormula:\ncount ~ s(weekday_num, bs = \"cc\", k = 7) + s(month_num, bs = \"cc\", \n    k = 12) + s(tmax) + s(tmin)\n\nParametric coefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) 2.640174   0.007836   336.9   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nApproximate significance of smooth terms:\n                 edf Ref.df Chi.sq p-value    \ns(weekday_num) 4.667  5.000 171.23 < 2e-16 ***\ns(month_num)   8.652 10.000  77.87 < 2e-16 ***\ns(tmax)        2.533  3.242  16.85 0.00108 ** \ns(tmin)        1.007  1.013   5.68 0.01748 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR-sq.(adj) =  0.141   Deviance explained = 14.9%\n-REML =   4809  Scale est. = 1         n = 1643\n```\n\n\n:::\n:::\n\nThe GAM model improves upon the linear model by capturing non-linear relationships between predictors and accident counts. All smooth terms are statistically significant (p <0.05), some more than others (e.g. week_day compared to tmin) and the deviance explained is higher than in the linear model's R-squared.\n\n### Plot of fitted versus actuals\nThis plot shows the plotted points now have a diagonal alignment closer to the actual=fitted line. This is an improvement compared to  the linear model.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngam_nb_results$Fitted_transformed <- exp(gam_nb_results$.fitted)\n\nggplot(gam_nb_results, aes(x = count, y = Fitted_transformed)) +\n  geom_point(alpha = 0.6, color = \"darkgreen\") +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"red\", size = 1.0) +\n  labs(title = \"Actual vs Transformed Fitted Values (GAM)\", x = \"Actual\",\n       y = \"Fitted (transformed)\") +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-39-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n### Plot of residuals versus fitted\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals(gam_nb)\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-40-1.png){fig-align='center' width=576}\n:::\n:::\n\nThe residuals are scattered fairly evenly around the zero line, suggesting the model is not systematically over- or under-predicting, which is good.\nMost of the residuals fall within ±2, and the spread is symmetric, supporting the assumption that the model errors are random and unbiased.\n\nThe residual plot for the GAM shows no obvious patterns or violations of model assumptions. Residuals are randomly distributed around zero, indicating that the GAM provides a better fit than the linear model. This supports the use of a non-linear approach for modeling accident counts.\n\n\n### Residuals vs Weekday number\nThe residuals vs weekday plot shows no obvious structure or seasonal bias, indicating that the GAM model has effectively accounted for weekday variation in accident counts. This supports the adequacy of the model fit and suggests no major violations of model assumptions.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = gam_nb, feature = \"weekday_num\", label = \"Weekday\",\n                      sub_label=\" (1=Mon, ..., 7=Sun)\", model_label=\"(GAM)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n### Residuals vs Month number\nThe residuals vs month plot shows no obvious structure or seasonal bias, indicating that the GAM model has effectively accounted for monthly variation in accident counts. This supports the adequacy of the model fit and suggests no major violations of model assumptions.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = gam_nb, feature = \"month_num\", label = \"Month\",\n                      sub_label=\" (1=Jan, ..., 12=Dec)\", model_label=\"(GAM)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=576}\n:::\n:::\n\n### Residuals vs Maximum temperature\nThe residuals vs tmax plot shows no strong structure or trend, indicating that the GAM model has effectively accounted for the influence of maximum temperature on accident counts. This supports the adequacy of the model fit and suggests no major violations of assumptions related to this predictor.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = gam_nb, feature = \"tmax\", label = \"Maximum Temperature\",\n                      sub_label=\"\", model_label=\"(GAM)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-43-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n### Residuals vs Minimum temperature\nThe residuals vs tmin plot shows no strong structure or trend, indicating that the GAM model has effectively accounted for the influence of minimum temperature on accident counts. This supports the adequacy of the model fit and suggests no major violations of assumptions related to this predictor.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_residuals_v_feat(model = gam_nb, feature = \"tmin\", label = \"Minium Temperature\",\n                      sub_label=\"\", model_label=\"(GAM)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n## Q7.4\n### Answer\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAIC(lm_model1, gam_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                df      AIC\nlm_model1  6.00000 9765.983\ngam_nb    20.18532 9566.777\n```\n\n\n:::\n:::\n\n\nBased on the AIC values, the GAM model with a Negative Binomial distribution (AIC = 9566.77) outperforms the linear model (AIC = 9765.983). This indicates that the GAM provides a better fit to the data while appropriately accounting for over-dispersion and non-linear relationships.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plot weekday\nplot(gam_nb, select = 1, shade = TRUE, main = \"Weekday\",\n     xlab = \"Weekday (1=Mon, ..., 7=Sun)\", ylab = \"Effect on log(count)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-46-1.png){fig-align='center' width=576}\n:::\n\n```{.r .cell-code}\n# Plot month\nplot(gam_nb, select = 2, shade = TRUE, main = \"Month\",\n     xlab = \"Month (1=Jan, ..., 12=Dec)\", ylab = \"Effect on log(count)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-46-2.png){fig-align='center' width=576}\n:::\n\n```{.r .cell-code}\n# Plot maximum temperature\nplot(gam_nb, select = 3, shade = TRUE, main = \"Maximum temperature\",\n     xlab = \"Temperature (\\u00B0C)\", ylab = \"Effect on log(count)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-46-3.png){fig-align='center' width=576}\n:::\n\n```{.r .cell-code}\n# Plot minimum temperature\nplot(gam_nb, select = 4, shade = TRUE, main = \"Minimum temperature\",\n     xlab = \"Temperature (\\u00B0C)\", ylab = \"Effect on log(count)\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-46-4.png){fig-align='center' width=576}\n:::\n:::\n\n\nThe smooth term for weekday reveals a weekly pattern in road traffic accidents, with highest counts on Fridays, and lowest counts on Sundays. This suggests that weekday is a meaningful predictor, likely capturing weekly driving conditions or travel behavior.\n\nThe smooth term for month reveals a seasonal pattern in road traffic accidents, with higher counts in late summer and late winter, and lower counts in autumn and early spring. This suggests that month of the year is a meaningful predictor, likely capturing seasonal driving conditions, weather, or travel behavior.\n\nThe smooth term for tmax suggests that accident counts tend to increase with rising temperatures up to around 30°C. This could reflect increased road usage or riskier driving conditions in warmer weather. However, the effect plateaus at very high temperatures, possibly due to behavioral changes (e.g., fewer people driving in extreme heat).\n\nThe smooth term for tmin indicates that lower minimum temperatures are associated with increased road traffic accidents. This could reflect hazardous driving conditions such as frost, fog, or reduced visibility during colder periods.\n\n### Q7.5\n### Answer\nResiduals were analyzed from the GAM model fitted using a Negative Binomial distribution and log link, with smooth terms for weekday_num, month_num, tmax, and tmin. The residuals vs fitted values plot shows residuals scattered fairly evenly around zero, with no clear trend or curvature. Most residuals fall within ±2, and the spread appears symmetric.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(residuals(gam_nb, type = \"deviance\"), type = \"l\",\n     main = \"Residuals Over Time\", ylab = \"Deviance Residuals\", xlab = \"Time Index\")\nabline(h = 0, col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-47-1.png){fig-align='center' width=576}\n:::\n\n```{.r .cell-code}\nacf(residuals(gam_nb, type = \"deviance\"), main = \"ACF of Residuals\")\n```\n\n::: {.cell-output-display}\n![](task9_files/figure-html/unnamed-chunk-47-2.png){fig-align='center' width=576}\n:::\n:::\n\nThe residuals over time plot shows noticeable fluctuations and clustering, suggesting that the residuals are not entirely random. Combined with the ACF plot, this indicates the presence of autocorrelation and potential un-modelled temporal structure. Further refinement of the model, such as including lagged predictors or additional time-based features, may help address this. The drop in residuals towards the end of the time series is during the COVID-19 period when Victoria had lock down and restrictions on travel.\n\nThe ACF plot of residuals shows significant autocorrelation at lag 0 and some early lags, as indicated by vertical bars exceeding the 95% confidence bounds. This suggests that the residuals are not entirely independent and that the model may not have fully captured the temporal structure in the data. Further refinement, such as including lagged predictors or temporal smoothing, may be necessary to improve model fit.\n\n### Q7.6\n### Answer\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngam_nb_ehf = gam(\n  count ~ s(weekday_num, bs=\"cc\", k=7) + s(month_num, bs=\"cc\", k=12) \n          + s(tmax) + s(tmin) + s(EHF),\n  family=nb(link = \"log\"),\n  data = merged_df,\n  knots = list(weekday_num = c(1, 8),  # wrap from 7 to 1\n               month_num = c(1, 13)    # wrap from 12 to 1\n  ))\n\nsummary(gam_nb_ehf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFamily: Negative Binomial(34.545) \nLink function: log \n\nFormula:\ncount ~ s(weekday_num, bs = \"cc\", k = 7) + s(month_num, bs = \"cc\", \n    k = 12) + s(tmax) + s(tmin) + s(EHF)\n\nParametric coefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) 2.640139   0.007836   336.9   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nApproximate significance of smooth terms:\n                 edf Ref.df  Chi.sq  p-value    \ns(weekday_num) 4.667  5.000 171.973  < 2e-16 ***\ns(month_num)   8.636 10.000  76.264  < 2e-16 ***\ns(tmax)        2.311  2.975  17.579 0.000528 ***\ns(tmin)        1.005  1.010   5.424 0.020132 *  \ns(EHF)         1.459  1.785   1.248 0.383222    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR-sq.(adj) =  0.141   Deviance explained = 14.9%\n-REML = 4812.2  Scale est. = 1         n = 1643\n```\n\n\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAIC(gam_nb, gam_nb_ehf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 df      AIC\ngam_nb     20.18532 9566.777\ngam_nb_ehf 22.29667 9569.528\n```\n\n\n:::\n:::\n\n\nAdding EHF to the GAM model did not improve model fit. The AIC increased slightly (from 9566.777 to 9569.528), and the smooth term for EHF was not statistically significant (p = 0.3832). Therefore, EHF does not appear to be a useful predictor for road traffic accident counts in this context.\n\n### Q7.7\n### Answer\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngam_nb_prcp = gam(\n  count ~  s(weekday_num, bs=\"cc\", k=7) + s(month_num, bs=\"cc\", k=12)\n         + s(tmax) + s(tmin)+ s(prcp),\n  family=nb(link = \"log\"),\n  data = merged_df,\n  knots = list(weekday_num = c(1, 8),  # wrap from 7 to 1\n               month_num = c(1, 13)    # wrap from 12 to 1\n  ))\n\nsummary(gam_nb_prcp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFamily: Negative Binomial(34.838) \nLink function: log \n\nFormula:\ncount ~ s(weekday_num, bs = \"cc\", k = 7) + s(month_num, bs = \"cc\", \n    k = 12) + s(tmax) + s(tmin) + s(prcp)\n\nParametric coefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) 2.640026   0.007827   337.3   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nApproximate significance of smooth terms:\n                 edf Ref.df  Chi.sq p-value    \ns(weekday_num) 4.666  5.000 170.135 < 2e-16 ***\ns(month_num)   8.677 10.000  80.537 < 2e-16 ***\ns(tmax)        2.680  3.426  21.199 0.00020 ***\ns(tmin)        1.003  1.006   6.933 0.00854 ** \ns(prcp)        1.048  1.094   4.329 0.03953 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nR-sq.(adj) =  0.143   Deviance explained = 15.1%\n-REML = 4810.7  Scale est. = 1         n = 1643\n```\n\n\n:::\n:::\n\n### Comparsion of AIC values\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAIC(gam_nb, gam_nb_prcp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  df      AIC\ngam_nb      20.18532 9566.777\ngam_nb_prcp 22.07495 9565.361\n```\n\n\n:::\n:::\n\n\nEHF was tested as a predictor but did not improve model fit, as indicated by a higher AIC and a non-significant smooth term. To explore alternatives, precipitation (prcp) was added to the model. It improved the fit marginally, with a lower AIC (9565.361) and a significant effect (p = 0.0395). Due to the lack of additional weather data for Moorabbin Airport, no further predictors could be tested. Based on available data, temperature variables (tmax and tmin) and precipitation (prcp) are the most predictive weather features for road traffic accidents.\n\n\n\\newpage\n# Q8\n\n## Project Reflection Report\nThis report reflects on the statistical modelling of road traffic accidents, addressing potential model improvements, the handling of common data issues, and an overall assessment of the analysis objectives.\n\n## Q8.1: Additional data for model improvement\nThe current model relies on weather and time data for its forecast. To make it more predictive in value and useful in the real world, some additional sources of data might be included:\n\n1. Traffic Volume Information: The traffic volume on the road is one determinant of the likelihood of accidents. Adding traffic loop detector data or GPS mobility data would provide a direct measure of risk exposure. A holiday with little traffic on a wet day, for example, might have a different accident risk than a wet day with heavy commuter traffic.\n\n2. Public Events and Holidays: Big sporting events, festivals, and concerts produce big deviations in traffic volumes and driver behavior. An indicator variable for such an event would be capable of modeling these such abnormal spikes in demand. On the same principle, it would be preferable to have public and school holiday indicator variables included directly instead of including month effects.\n\n3. Road Conditions and Infrastructure: Information regarding roadworks, diversions, road condition, and blackspots where accidents are known to occur can be useful predictors. Some of these will be unchanging, but information regarding temporary roadworks will often be present and extremely relevant.\n\n4. Additional Weather Metrics: In addition to temperature, visibility is also crucial, as poor visibility due to fog or heavy precipitation may increase accident risk. Wind speed and gusts can significantly impact vehicle control, particularly for larger or lighter vehicles. Cloud cover and solar radiation significantly impact visibility and glare, especially during sunrise or sunset. Including these variables helps capture the complex ways weather impacts driving safety.\n\n## Q8.2: Achievement of analysis objectives\nYes, the analyses have successfully addressed the objective of predicting the daily number of road traffic accidents in a selected region of Victoria using weather and temporal data. The goal was to develop a model that supports emergency service planning and public safety forecasting by identifying patterns in accident risk based on forecastable variables.\n\nThe first baseline linear model helped identifying statistically significant predictors, including maximum and minimum temperatures, as well as the week day and month. However, the model explained only a small portion of the variance (adjusted R-squared of approximately 0.034), indicating that a linear approach was insufficient to account for the data.\n\nTo improve predictive performance, a Negative Binomial GAM was fitted. This model captured non-linear relationships and significantly improved the fit, with a higher adjusted R-squared (approximately 0.141), greater deviance explained (approximately 14.9%), and a lower AIC. The importance of the temperature, weekday and month predictors was confirmed through statistical significance.\n\nAdditional predictors were explored to make the model more precise. The Extreme Heat Factor (EHF) was tested but failed to improve the model, as indicated by a larger AIC and a non-significant smooth term. Precipitation was also attempted and was able to improve upon the model, with an decreased AIC (9565.361 vs. 9566.777) and significant effect (p = 0.03953). Due to limited weather data availability for Moorabbin Airport, no further predictors could be tested.\n\nWhile the percentage of deviance explained is modest, the modelling is still a success for several reasons:\n\n* Real-world accident data is inherently noisy and influenced by many unobserved factors, such as driver behaviour, traffic volume, and road conditions.\n\n* The model identified statistically significant and interpretable relationships using forecastable variables.\n\n* It improved upon the baseline model and demonstrated that temperature, weekday and month are meaningful predictors.\n\n* The model is practical for short-term forecasting, aligning with the original objective of supporting emergency service planning.\n\n\n## Q8.3: Handling missing values\nIf the dataset contained missing values, several methods could be employed to address the issue, ranging from simple to complex. The choice of method depends on the extent and nature of the value that is missing (the missingness).\n\n1. Complete Case Analysis or Listwise Deletion: It is the simplest method,  involving removal of any row that has a missing value[1]. If the data is missing completely at random (MCAR), then listwise deletion \"produces unbiased estimates of means, variances and regression weights\" [1]. It the data is not MCAR can significantly reduce statistical power and introduce bias. The main disadvantage of listwise deletion is the loss of data as the entire case (row) is removed.\n\n2. Single Imputation: In this approach, missing data is replaced by a single reasonable substitute [1]. Some common methods of selecting an acceptable substitute include replacing by the mean, median, or mode of the variable, adopting forward or backward filling methods[2]. Another sophisticated technique is regression imputation [1], wherein a regression model for imputation of the missing values is developed from other available variables.\n\n3. Multiple Imputation (MI): MI is known to be very effective and \"accepted as the best general method to deal with incomplete data in many fields\"[1]. Instead of replacing a single value for missing observations, MI creates several plausible values for every missing entry, thus creating several complete data sets. Each of these imputed data sets is analysed for results that are then combined using existing guidelines (e.g., Rubin's rules)[1]. This approach correctly takes into account the statistical uncertainty of the missing data such that greater precision of standard error and confidence intervals is obtained.\n\nIn this work, the dataset contained a small number of missing values that required handling before analysis. Several methods were considered to address this incomplete data. Given the extremely small proportion of missing traffic accident data (less than 0.25%), median imputation was a pragmatic and robust choice that avoids the unnecessary complexity of multiple imputation. For the missing temperature data, forward filling was used to preserve the temporal context, as the temperature from the previous day is a more logical estimate for a time-series than a simple statistical average of the entire dataset.\n\n\n## Q8.4: Tackling over-fitting from explanatory variables\nOver-fitting occurs when a model captures noise or random fluctuations in the training data, resulting in poor generalisation to new data. In the context of Generalised Additive Models (GAMs), over-fitting can arise from using too many explanatory variables or overly flexible smooth terms.\n\nTo manage an excessive number of explanatory variables in a GAM and prevent over-fitting, two primary, complementary strategies can be employed: automatic feature selection via shrinkage smoothers and explicit model selection using information criteria, such as AIC.\n\nAutomatic Feature Selection (via Shrinkage): This is the most integrated approach. By using special \"shrinkage\" smoothers (e.g., by setting select=TRUE in R's `mgcv` package), you introduce a penalty that can shrink the smooth functions of irrelevant variables completely to zero [3],[4]. This effectively performs automatic feature selection during the model fitting process, allowing you to include many candidate variables and let the model determine which ones are important.\n\nModel Comparison and Selection (via AIC): The Akaike Information Criterion (AIC) is a widely used tool for balancing model fit and complexity. AIC penalises models with more parameters, helping to avoid over-fitting by favouring simpler models that still explain the data well [5]. You can perform a stepwise variable selection process by fitting models with different subsets of variables and choosing the model with the lowest AIC. Cross-validation with an error metric such as RMSE can be used as an alternative to AIC, but it would be more computationally expensive.\n\nBy applying these strategies, using shrinkage smoothers for automatic selection and  performing manual elimination you can effectively and justifiably reduce the number of explanatory variables in your GAM to create a simpler and robust model.\n\nIn this work, only the model comparison and selection strategy using AIC for comparison of models was employed.\n\n\n## References\n[1] S. van Buuren, Flexible Imputation of Missing Data, Second Edition. Second edition. | Boca Raton, Florida : CRC Press, [2019] |: Chapman and Hall/CRC, 2018. doi: https://doi.org/10.1201/9780429492259.\n\n[2] H. Wickham, R. François, L. Henry, K. Müller, and D. Vaughan, “dplyr: A Grammar of Data Manipulation,” dplyr.tidyverse.org, 2025. https://dplyr.tidyverse.org\n\n[3] S. Wood, “Help for package mgcv,” R-project.org, 2017. https://cran.r-project.org/web/packages/mgcv/refman/mgcv.html#gam (accessed Sep. 26, 2025).\n\n[4] S. N. Wood, Generalized additive models : an introduction with R. Boca Raton Etc.: Crc Press - Taylor &Francis Group, 2017.\n\n[5]J. E. Cavanaugh and A. A. Neath, “The Akaike information criterion: Background, derivation, properties, application, interpretation, and refinements,” Wiley Interdisciplinary Reviews: Computational Statistics, vol. 11, no. 3, pp. 1–11, Mar. 2019, doi: https://doi.org/10.1002/wics.1460.\n\n",
    "supporting": [
      "task9_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}