{
  "hash": "89e57923feff0e77156991e00adb983d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Electricity Grid\"\njupyter: python3\n---\n\n::: {#1b647624 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport warnings\n\n# Suppress all UserWarnings\nwarnings.filterwarnings(\"ignore\", category=UserWarning)\n```\n:::\n\n\n# Introduction\nThis notebook investigates SVM and decision tree models.\n\n# Data pre-processing\n\n## Data\nThe dataset used in this notebook is the [Electrical Grid Stability Simulated Data](https://archive.ics.uci.edu/dataset/471/electrical+grid+stability+simulated+data) from the UC Irvine Machine Learning Repository. The data is licensed under CC BY, allowing it to be freely used for this exercise.\n\nThe dataset contains data from the local stability analysis of the 4-node star system implementing the Decentral Smart Grid Control concept. The data comprises 12 features and two labelled variables, \"stab\" and \"stabf\", which indicate the stability label of the system. For this work, \"stabf\" is used as the target variable.\n\n### Load data\nThe data is loaded into a pandas dataframe from the downloaded CSV file. After loading the data, the first five rows of the dataframe are inspected using the head() function. The dataframe is then checked for any missing values. This dataset is clean with no missing values.\n\n::: {#eb5d9255 .cell execution_count=2}\n``` {.python .cell-code}\n# Load the data file into a dataframe\ndf = pd.read_csv(\"Data_for_UCI_named.csv\", comment=\"#\")\n\n# Inspect the head of the data\nprint(df.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       tau1      tau2      tau3      tau4        p1        p2        p3  \\\n0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   \n1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   \n2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   \n3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   \n4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   \n\n         p4        g1        g2        g3        g4      stab     stabf  \n0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  \n1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  \n2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  \n3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  \n4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable  \n```\n:::\n:::\n\n\n### Drop irrelevant features\nThe dataset metadata states that the \"stab\" is also a target variable, the continuous representation of \"stabf\".\n\n::: {#6ec4f72a .cell execution_count=3}\n``` {.python .cell-code}\ndf.drop([\"stab\"], axis=1, inplace=True)\n```\n:::\n\n\n### Check for null values\n\n::: {#5e8fb05d .cell execution_count=4}\n``` {.python .cell-code}\n# Check how many null values are in the data frame\nprint()\nprint(\"Feature Name           Number of missing entries\")\nprint(df.isnull().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFeature Name           Number of missing entries\ntau1     0\ntau2     0\ntau3     0\ntau4     0\np1       0\np2       0\np3       0\np4       0\ng1       0\ng2       0\ng3       0\ng4       0\nstabf    0\ndtype: int64\n```\n:::\n:::\n\n\n### Check for duplicate values\n\n::: {#bf80aed2 .cell execution_count=5}\n``` {.python .cell-code}\n# Count duplicate rows\nduplicate_count = df.duplicated().sum()\n\nprint(f\"Number of duplicate rows: {duplicate_count}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of duplicate rows: 0\n```\n:::\n:::\n\n\n### Check datatypes\nThis shows that all features are numerical, therfore no feature encoding is required.\n\n::: {#c8cf0557 .cell execution_count=6}\n``` {.python .cell-code}\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 10000 entries, 0 to 9999\nData columns (total 13 columns):\n #   Column  Non-Null Count  Dtype  \n---  ------  --------------  -----  \n 0   tau1    10000 non-null  float64\n 1   tau2    10000 non-null  float64\n 2   tau3    10000 non-null  float64\n 3   tau4    10000 non-null  float64\n 4   p1      10000 non-null  float64\n 5   p2      10000 non-null  float64\n 6   p3      10000 non-null  float64\n 7   p4      10000 non-null  float64\n 8   g1      10000 non-null  float64\n 9   g2      10000 non-null  float64\n 10  g3      10000 non-null  float64\n 11  g4      10000 non-null  float64\n 12  stabf   10000 non-null  object \ndtypes: float64(12), object(1)\nmemory usage: 1015.8+ KB\n```\n:::\n:::\n\n\n## Target encoding\n\n::: {#4cd7c73d .cell execution_count=7}\n``` {.python .cell-code}\ndf = df.rename(columns={\"stabf\": \"target\"})\n\n# Create label mapping\ntarget_mapping = {\"unstable\": 0, \"stable\": 1}\n\n# Apply the mapping\ndf[\"target\"] = df[\"target\"].map(target_mapping)\n\ndf.head(5)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>tau1</th>\n      <th>tau2</th>\n      <th>tau3</th>\n      <th>tau4</th>\n      <th>p1</th>\n      <th>p2</th>\n      <th>p3</th>\n      <th>p4</th>\n      <th>g1</th>\n      <th>g2</th>\n      <th>g3</th>\n      <th>g4</th>\n      <th>target</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2.959060</td>\n      <td>3.079885</td>\n      <td>8.381025</td>\n      <td>9.780754</td>\n      <td>3.763085</td>\n      <td>-0.782604</td>\n      <td>-1.257395</td>\n      <td>-1.723086</td>\n      <td>0.650456</td>\n      <td>0.859578</td>\n      <td>0.887445</td>\n      <td>0.958034</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>9.304097</td>\n      <td>4.902524</td>\n      <td>3.047541</td>\n      <td>1.369357</td>\n      <td>5.067812</td>\n      <td>-1.940058</td>\n      <td>-1.872742</td>\n      <td>-1.255012</td>\n      <td>0.413441</td>\n      <td>0.862414</td>\n      <td>0.562139</td>\n      <td>0.781760</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>8.971707</td>\n      <td>8.848428</td>\n      <td>3.046479</td>\n      <td>1.214518</td>\n      <td>3.405158</td>\n      <td>-1.207456</td>\n      <td>-1.277210</td>\n      <td>-0.920492</td>\n      <td>0.163041</td>\n      <td>0.766689</td>\n      <td>0.839444</td>\n      <td>0.109853</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>0.716415</td>\n      <td>7.669600</td>\n      <td>4.486641</td>\n      <td>2.340563</td>\n      <td>3.963791</td>\n      <td>-1.027473</td>\n      <td>-1.938944</td>\n      <td>-0.997374</td>\n      <td>0.446209</td>\n      <td>0.976744</td>\n      <td>0.929381</td>\n      <td>0.362718</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>3.134112</td>\n      <td>7.608772</td>\n      <td>4.943759</td>\n      <td>9.857573</td>\n      <td>3.525811</td>\n      <td>-1.125531</td>\n      <td>-1.845975</td>\n      <td>-0.554305</td>\n      <td>0.797110</td>\n      <td>0.455450</td>\n      <td>0.656947</td>\n      <td>0.820923</td>\n      <td>0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Dataset balance\nHere, I inspect the balance of the classes in the full dataset. The figure below shows there are more unstable's (0) and stables's (1). However, the dataset balance is reasonable and doesn't require any further treatment. \n\n::: {#8e4c39a3 .cell execution_count=8}\n``` {.python .cell-code}\n# Count distribution of 0s and 1s\ntarget_counts = df[\"target\"].value_counts()\n\n# Plot the distribution\nplt.figure(figsize=(6, 4))\ntarget_counts.plot(kind=\"bar\", color=[\"skyblue\", \"orange\"])\nplt.title(\"Distribution of Target Variable\")\nplt.xlabel(\"Target Class\")\nplt.ylabel(\"Count\")\nplt.xticks(ticks=[0, 1], labels=[\"0 (unstable)\", \"1 (stable)\"], rotation=0)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-9-output-1.png){}\n:::\n:::\n\n\n## Train test split\nStratified sampling has been used to ensure the class proportions remain the same in the test and train sets.\n\n::: {#17dbbcf1 .cell execution_count=9}\n``` {.python .cell-code}\nfrom sklearn.model_selection import StratifiedShuffleSplit\nfrom sklearn.preprocessing import StandardScaler\n\n# Split the data\n# Stratified sampling to help maintain similar distributions between the text and train sets\nstratSplit = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=8)\nfor train_index, test_index in stratSplit.split(df.iloc[:, :-1], df[\"target\"]):\n    X_train = df.iloc[:, :-1].iloc[train_index]\n    X_test = df.iloc[:, :-1].iloc[test_index]\n    y_train = df[\"target\"].iloc[train_index]\n    y_test = df[\"target\"].iloc[test_index]\n\n# Fit scaler on training data\nscaler = StandardScaler()\nX_train_scald = scaler.fit_transform(X_train)\n\n# Transform test data using the same scaler\nX_test_scald = scaler.transform(X_test)\n\n# check class distribution in test set\ntest_counts = y_test.value_counts()\n\n# check null accuracy score\nnull_accuracy = (test_counts[0]/(test_counts[0] + test_counts[1]))\n\nprint(f\"Null accuracy score: {null_accuracy:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNull accuracy score: 0.6380\n```\n:::\n:::\n\n\n# SVM\nHere, support vector machine (SVM) models are fitted. The Support Vector Classifier (SVC) model in scikit learn has several hyperparameters. The hyperparameters can be divided into general and kernel-specific.\n\n**General SVM hyperparameters**:\n  * Kernel: Options are \"linear\", \"RBF\", \"poly\" and \"sigmoid.\n  * C: Regularisation parameter. Controls the trade-off between accuracy and generalisation.\n     - High values create tighter decision boundaries (risk of overfitting).  \n     - Low values allow smoother decision boundaries (risk of underfitting).\n  * Class Weight: Useful for imbalanced datasets.\n\n**Kernel-specific hyperparameters**:\n  * \"gamma\": Influence of individual data points. Available in \"RBF\", \"poly\", \"sigmoid\".\n     - Higher values make the model focus on local structures (risk of overfitting).\n     - Lower values create smoother decision boundaries.\n  * \"coef0\": Controls curve shift in polynomial/sigmoid kernels.\n     - Impacts feature interactions.\n  * \"degree\": Defines the complexity of polynomial curves.\n     - Higher degrees create more flexible decision boundaries.\n * Class Weight: Useful for imbalanced datasets.\n\nFor this task, we have been asked to focus on:\n\n * the kernel type - selecting three kernels.\n * the regularisation parameter C.\n\nI have performed hyperparameter optimisation to find the combination of parameters that gives the best model performance. For the model evaluation, I have used the weighted F1 score. F1 is the harmonic mean of precision and recall.\n\n## Kernel\nFor this section, I have focused on three kernels, \"linear\", \"poly\" and \"RBF\". For each kernel, I have performed hyperparameter optimisation to find the combination of parameters that gives the best model performance using the following parameters: \n\n  * \"class_weight\": Applicable to all kernels.\n  * \"gamma\": Applicable to \"RBF\" and \"poly\".\n  * \"coef0\" and \"degree\": Applicable only to \"poly\".\n\nAll other hyperparameters not subject to the optimisation were left at their default values.\n\nThe search for optimal parameter combinations used the BayesSearchCV method. For each kernel, the best parameters are used to measure the model's performance by plotting a confusion matrix and printing a summary of the accuracy, precision, recall and F1-score.\n\n::: {#412d2e04 .cell execution_count=10}\n``` {.python .cell-code}\nfrom skopt import BayesSearchCV\nfrom sklearn.model_selection import StratifiedKFold, GridSearchCV\nfrom sklearn.svm import SVC\nfrom sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix\n\n# Create base search space\nsearch_space = {\"class_weight\": [None, \"balanced\"]}\n\n# RBF and poly specific parameters\nrbf_search_space = {\"gamma\": (1e-4, 0.1, 'log-uniform')}\n\n# Poly specific parameters\npoly_search_space = {\n    \"degree\": (2, 5),\n    \"coef0\": (-1, 1)\n}\n\n# Define kernels\nkernels = [\"linear\", \"rbf\", \"poly\"]\n\n# Store results\nresults_kern = []\n\nclasses = [\"0 (unstable)\", \"1 (stable)\"]\n\ncv = StratifiedKFold(n_splits=5)\n\nfor kernel in kernels:\n    # Create model\n    svc_model = SVC(kernel=kernel, probability=False, verbose=True, random_state=0)\n    \n    if kernel == \"rbf\":        \n        search_space.update(rbf_search_space)\n    elif kernel == \"poly\":\n        search_space.update(poly_search_space)\n\n    opt = BayesSearchCV(\n        svc_model,\n        search_spaces=search_space,\n        scoring=\"f1_weighted\",\n        cv=cv,\n        n_iter=10,  # Number of iterations\n        n_jobs=-1,  # Use all cores\n        verbose=0,\n        random_state=0\n    )\n\n    opt.fit(X_train, y_train)  \n\n    # Get best parameters from BayesSearch\n    best_params = opt.best_params_\n    print(f\"\\nHyperparameters {kernel}: {best_params}\")\n     \n    # Train model using best parameters\n    best_model_kern = SVC(kernel=kernel, random_state=0, **best_params)\n    best_model_kern.fit(X_train, y_train)\n\n    # Predict on test set\n    y_pred = best_model_kern.predict(X_test)\n\n    # Compute metrics\n    accuracy = accuracy_score(y_test, y_pred)\n    precision = precision_score(y_test, y_pred, average=\"weighted\")\n    recall = recall_score(y_test, y_pred, average=\"weighted\")\n    f1 = f1_score(y_test, y_pred, average=\"weighted\")\n\n    # Store results\n    results_kern.append({\n        \"Kernel\": kernel,\n        \"Accuracy\": accuracy,\n        \"Precision\": precision,\n        \"Recall\": recall,\n        \"F1-score\": f1,\n        \"Best Hyperparameters\": best_model_kern.get_params()\n    })\n\n    # Plot Confusion Matrix\n    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])\n    plt.figure(figsize=(6, 5))\n    sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\", xticklabels=classes, yticklabels=classes)\n    plt.xlabel(\"Predicted Labels\")\n    plt.ylabel(\"Actual Labels\")\n    plt.title(f\"SVM Confusion Matrix - Kernel: {kernel}\")\n    plt.show()\n\n# Convert results into a DataFrame\nresults_svm_kern_df = pd.DataFrame(results_kern)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[LibSVM]\nHyperparameters linear: OrderedDict([('class_weight', None)])\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-11-output-2.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[LibSVM]\nHyperparameters rbf: OrderedDict([('class_weight', None), ('gamma', 0.04881101667405022)])\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-11-output-4.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[LibSVM]\nHyperparameters poly: OrderedDict([('class_weight', None), ('coef0', 1), ('degree', 4), ('gamma', 0.06314005836673514)])\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-11-output-6.png){}\n:::\n:::\n\n\n::: {#46c02505 .cell execution_count=11}\n``` {.python .cell-code}\ndef print_performance_report_svm(df, param_keys_by_kernel):\n    \"\"\"\n    Function to print a performance report.\n\n    :param df: DataFame with performance data.\n    :param param_keys_by_kernel: Dictionary with paramters keys to print for each kernel.\n    :returns: None\n    \"\"\"\n    # Columns to print directly\n    selected_columns = [\"Kernel\", \"Accuracy\", \"Precision\", \"Recall\", \"F1-score\"]\n\n    # Define column widths for alignment\n    col_widths = {\"K\": 6, \"A\": 8, \"P\": 9, \"R\": 6, \"F\": 8}\n\n    # Print a header\n    print(f\"Kernel | Accuracy | Precision | Recall | F1-score | Best Parameters (searched)\")\n    print(\"-\" * 120)\n\n    # Loop through the DataFrame and print each row horizontally\n    for index, row in df.iterrows():\n        kernel = row[\"Kernel\"]\n        selected_keys = param_keys_by_kernel.get(kernel, [])\n        best_params_filtered = []\n        for key in selected_keys:\n            value = row[\"Best Hyperparameters\"].get(key)\n            if isinstance(value, float):\n                formatted_value = f\"{value:.4f}\"\n            else:\n                formatted_value = str(value)\n            best_params_filtered.append(f\"{key}: {formatted_value}\")\n        line = f\"{kernel:<{col_widths['K']}} | {row['Accuracy']:<{col_widths['A']}.4f} | {row['Precision']:<{col_widths['P']}.4f} | {row['Recall']:<{col_widths['R']}.4f} | {row['F1-score']:<{col_widths['F']}.4f} | {', '.join(best_params_filtered)}\"\n        print(line)\n```\n:::\n\n\n::: {#601ccfa8 .cell execution_count=12}\n``` {.python .cell-code}\n# Define which keys to print from best hyperparameters based on kernel value\nparam_keys_kernel = {\n    \"linear\": [\"classs_weights\"],\n    \"rbf\": [\"classs_weights\", \"gamma\"],\n    \"poly\": [\"classs_weights\", \"gamma\", \"degree\", \"coef0\"]\n}\n\n# Display performance report\nprint(\"\\nPerformance Report:\")\n\nprint_performance_report_svm(results_svm_kern_df, param_keys_kernel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPerformance Report:\nKernel | Accuracy | Precision | Recall | F1-score | Best Parameters (searched)\n------------------------------------------------------------------------------------------------------------------------\nlinear | 0.8250   | 0.8231    | 0.8250 | 0.8232   | classs_weights: None\nrbf    | 0.9205   | 0.9206    | 0.9205 | 0.9198   | classs_weights: None, gamma: 0.0488\npoly   | 0.9775   | 0.9775    | 0.9775 | 0.9775   | classs_weights: None, gamma: 0.0631, degree: 4, coef0: 1\n```\n:::\n:::\n\n\nFrom the above table it is shown that the poynomial kernel gives the best performance across all metrics.\n\n## Regularisation strength - C\n\n::: {#53c250e3 .cell execution_count=13}\n``` {.python .cell-code}\n# Create base search space\nparam_grid = {\"C\": [0.01, 0.1, 1, 10, 100, 1000]}\n\n# Store results\nresults_C= []\n\n# Dictionary to store cross-validation results.\nscores = {}\n\nfor kernel in kernels:\n    print(f\"Kernel: {kernel}\")\n\n    # Get best parameters from previous section\n    best_params_kern = results_svm_kern_df.loc[results_svm_kern_df[\"Kernel\"] == kernel, \"Best Hyperparameters\"].values[0].copy()\n\n    # Remove the \"C\", we are testing it here\n    best_params_kern.pop(\"C\", None)\n\n    # Create model\n    svc_model = SVC(**best_params_kern)\n\n    # Set up GridSearchCV\n    # GridSearchCV uses stratified sampling internally, so no special action is required.\n    # Interested in performance for all classes, so use the macro option\n    grid_search = GridSearchCV(svc_model, param_grid, cv=5, scoring=\"f1_weighted\", n_jobs=-1,\n                               return_train_score=True)\n\n    # Fit the model\n    grid_search.fit(X_train, y_train)\n\n    # Store all results for this kernel\n    scores[kernel] = grid_search.cv_results_\n\n    # Get best parameters from GridSearch\n    best_params_C = grid_search.best_params_\n\n    # Add the best C to the current parameters    \n    best_params = best_params_kern | best_params_C\n \n    print(f\"\\nHyperparameters {kernel}: {best_params_C}\")\n     \n    # Train model using best parameters\n    best_model = SVC(**best_params)\n    best_model.fit(X_train, y_train)\n\n    # Predict on test set\n    y_pred = best_model.predict(X_test)\n\n    # Compute metrics\n    accuracy = accuracy_score(y_test, y_pred)\n    precision = precision_score(y_test, y_pred, average=\"weighted\")\n    recall = recall_score(y_test, y_pred, average=\"weighted\")\n    f1 = f1_score(y_test, y_pred, average=\"weighted\")\n\n    # Store results\n    results_C.append({\n        \"Kernel\": kernel,\n        \"Accuracy\": accuracy,\n        \"Precision\": precision,\n        \"Recall\": recall,\n        \"F1-score\": f1,\n        \"Best Hyperparameters\": best_model.get_params()\n    })\n\n    # Plot Confusion Matrix\n    cm = confusion_matrix(y_test, y_pred, labels=[0,1])\n    plt.figure(figsize=(6, 5))\n    sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\", xticklabels=classes, yticklabels=classes)\n    plt.xlabel(\"Predicted Labels\")\n    plt.ylabel(\"Actual Labels\")\n    plt.title(f\"SVM Confusion Matrix - Kernel: {kernel}\")\n    plt.show()\n\n# Convert results into a DataFrame\nresults_svm_C_df = pd.DataFrame(results_C)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nKernel: linear\n\nHyperparameters linear: {'C': 1}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-14-output-2.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nKernel: rbf\n\nHyperparameters rbf: {'C': 100}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-14-output-4.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nKernel: poly\n\nHyperparameters poly: {'C': 0.1}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-14-output-6.png){}\n:::\n:::\n\n\n::: {#2029f589 .cell execution_count=14}\n``` {.python .cell-code}\n# Plotting the results\nplt.figure(figsize=(10, 6))\nfor kernel, data in scores.items():\n    plt.plot(data[\"param_C\"], data[\"mean_test_score\"], marker=\"o\", label=kernel)\n\nplt.xscale(\"log\")\nplt.xlabel(\"C value (log scale)\")\nplt.ylabel(\"Mean Validation Score\")\nplt.title(\"Comparision of mean validation score versus C value for different SVM kernels\")\nplt.legend()\nplt.grid(True)\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-15-output-1.png){}\n:::\n:::\n\n\n::: {#7b45f77a .cell execution_count=15}\n``` {.python .cell-code}\nparam_keys_C = {\"linear\": [\"C\" ], \"rbf\": [\"C\"], \"poly\": [\"C\"]}\n\n# Display performance report\nprint(\"\\nPerformance Report:\")\n\nprint_performance_report_svm(results_svm_C_df, param_keys_C)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPerformance Report:\nKernel | Accuracy | Precision | Recall | F1-score | Best Parameters (searched)\n------------------------------------------------------------------------------------------------------------------------\nlinear | 0.8250   | 0.8231    | 0.8250 | 0.8232   | C: 1\nrbf    | 0.9630   | 0.9631    | 0.9630 | 0.9630   | C: 100\npoly   | 0.9755   | 0.9755    | 0.9755 | 0.9755   | C: 0.1000\n```\n:::\n:::\n\n\n# Decision Tree\nIn this section, I train a decision tree and tune its depth. Decision trees have many hyperparameters, but for this exercise, the tuning is limited to \"max_depth\". All other hyperparameters are left at their default values. \n\n::: {#c6e66082 .cell execution_count=16}\n``` {.python .cell-code}\nfrom sklearn.tree import DecisionTreeClassifier\n\n# Create base search space\ndt_param_grid = {\"max_depth\": range(1, 21)}\n\n# Store results\ndt_results= []\n\n# Create model\ndt_model = DecisionTreeClassifier(random_state = 0)\n\n# Set up GridSearchCV\n# GridSearchCV uses stratified sampling internally, so no special action is required.\n# Interested in performance for all classes, so use the macro option\ndt_grid_search = GridSearchCV(dt_model, dt_param_grid, cv=10, scoring=\"f1_weighted\", n_jobs=-1,\n                            return_train_score=True)\n\n# Fit the model\ndt_grid_search.fit(X_train, y_train)\n\n# Store all results\ndt_scores = dt_grid_search.cv_results_\n\n# Get best parameters from GridSearch\ndt_best_params = dt_grid_search.best_params_\n\nprint(f\"\\nHyperparameters: {dt_best_params}\")\n     \n# Train model using best parameters\ndt_best_model = dt_grid_search.best_estimator_\n\n# Predict on test set\ndt_y_pred = dt_best_model.predict(X_test)\n\n# Compute metrics\ndt_accuracy = accuracy_score(y_test, dt_y_pred)\ndt_precision = precision_score(y_test, dt_y_pred, average=\"weighted\")\ndt_recall = recall_score(y_test, dt_y_pred, average=\"weighted\")\ndt_f1 = f1_score(y_test, dt_y_pred, average=\"weighted\")\n\n# Store results\ndt_results.append({\n    \"Accuracy\": dt_accuracy,\n    \"Precision\": dt_precision,\n    \"Recall\": dt_recall,\n    \"F1-score\": dt_f1,\n    \"Best Hyperparameters\": dt_best_model.get_params()\n})\n\n# Plot Confusion Matrix\ndt_cm = confusion_matrix(y_test, dt_y_pred, labels=[0,1])\nplt.figure(figsize=(6, 5))\nsns.heatmap(dt_cm, annot=True, fmt=\"d\", cmap=\"Blues\", xticklabels=classes, yticklabels=classes)\nplt.xlabel(\"Predicted Labels\")\nplt.ylabel(\"Actual Labels\")\nplt.title(f\"Decision Tree Confusion Matrix\")\nplt.show()\n\n# Convert results into a DataFrame\nresults_dt_df = pd.DataFrame(dt_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nHyperparameters: {'max_depth': 10}\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-17-output-2.png){}\n:::\n:::\n\n\n::: {#4a387398 .cell execution_count=17}\n``` {.python .cell-code}\n# Plotting the results\nplt.figure(figsize=(10, 6))\nplt.plot(dt_scores[\"param_max_depth\"], dt_scores[\"mean_train_score\"], marker=\"o\", label=\"Training\")\nplt.plot(dt_scores[\"param_max_depth\"], dt_scores[\"mean_test_score\"], marker=\"o\", label=\"Validation\")\n\nplt.xlabel(\"Tree-depth\")\nplt.ylabel(\"Mean Score\")\nplt.title(\"Accuracy comparison of training/validation set\")\nplt.legend()\nplt.grid(True)\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task8_1P_files/figure-html/cell-18-output-1.png){}\n:::\n:::\n\n\n::: {#e1062bbd .cell execution_count=18}\n``` {.python .cell-code}\n# Columns to print directly\nselected_columns = [\"Accuracy\", \"Precision\", \"Recall\", \"F1-score\"]\n\n# Define column widths for alignment\ncol_widths = {\"A\": 8, \"P\": 9, \"R\": 6, \"F\": 8}\n\n# Print a header\nprint(f\"Accuracy | Precision | Recall | F1-score | Best Parameters (searched)\")\nprint(\"-\" * 120)\n\n# Loop through the DataFrame and print each row horizontally\nfor index, row in results_dt_df.iterrows():\n    value = row[\"Best Hyperparameters\"].get(\"max_depth\")\n    best_params_filtered = [f\"max_depth: {value}\"]\n    line = f\"{row['Accuracy']:<{col_widths['A']}.4f} | {row['Precision']:<{col_widths['P']}.4f} | {row['Recall']:<{col_widths['R']}.4f} | {row['F1-score']:<{col_widths['F']}.4f} | {', '.join(best_params_filtered)}\"\n    print(line)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAccuracy | Precision | Recall | F1-score | Best Parameters (searched)\n------------------------------------------------------------------------------------------------------------------------\n0.8510   | 0.8500    | 0.8510 | 0.8503   | max_depth: 10\n```\n:::\n:::\n\n\n# Hyperparameter tuning\n\n## The Role of Hyperparameters\nHyperparameters are model settings that control the learning process and determine model complexity. Hyperparameters are not learned directly from the data. Hyperparameter tuning in model development is an important step that involves identifying the optimal model parameters. Proper hyperparameter tuning improves model accuracy, generalisation, and efficiency. Tuned hyperparameters prevent overfitting and underfitting by selecting an appropriate model complexity.\n\n**Model-Specific Impact**: Different models have different hyperparameters. For SVMs, I tuned kernel-specific parameters (gamma, degree, coef0) and the regularisation parameter C. For Decision Trees, max_depth controls model complexity and overfitting.\n\n## Key Insights from my Results\n\n**Sequential vs. Joint Optimisation**: My approach for SVM, which involves first optimising kernel-specific parameters with C=1, then optimising C separately, shows a common strategy. However, this sequential approach may not find the global optimum since parameters often interact. Joint optimisation using techniques like GridSearchCV or BayesSearchCV across all parameters simultaneously would likely yield better results.\n\n**Regularisation Effects (C parameter)**:\n- Linear kernel: C=1 was optimal, suggesting the default regularisation worked well.\n- RBF kernel: C=100 (less regularisation) improved performance significantly (0.9205 to 0.9630).\n- Polynomial kernel: C=0.1 (more regularisation) was optimal, preventing overfitting in this complex kernel.\n\n**Kernel Complexity Hierarchy**: The results show the expected pattern: polynomial > RBF > linear in terms of model flexibility and performance on this dataset. The polynomial kernel achieved the highest performance (0.9775) but required strong regularisation (C=0.1).\n\n## Broader Hyperparameter Tuning Principles\n\n**Bias-Variance Tradeoff**: Hyperparameters control the balance between model complexity and generalisation. The Decision Tree's max_depth=10 represents finding the sweet spot between underfitting (too shallow) and overfitting (too deep).\n\n**Domain and Data Dependency**: Optimal hyperparameters are highly dataset-dependent. The fact that different kernels required different C values demonstrates why systematic tuning is essential rather than using defaults.\n\n**Validation Strategy**: Proper hyperparameter tuning requires robust validation (cross-validation) to ensure the selected parameters generalise well to unseen data, not just perform well on the training set.\n\n**Computational Efficiency**: Tuning fewer parameters at a time reduces computational cost but may sacrifice optimality, but is likely to be better than using the defaults.\n\n",
    "supporting": [
      "Task8_1P_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}