{
  "hash": "a3b05e2c938b0a39023c097a42969ea6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Liver Cirrhosis\"\njupyter: python3\n---\n\n::: {#4e5ed70e .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np \nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport shap\nimport warnings\nfrom collections import Counter\nfrom imblearn.over_sampling import SMOTE\nfrom skopt import BayesSearchCV\nfrom sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import GridSearchCV, learning_curve, StratifiedKFold, StratifiedShuffleSplit, cross_val_score\nfrom sklearn.metrics import f1_score, confusion_matrix, classification_report\nfrom sklearn.svm import SVC\nfrom sklearn.tree import DecisionTreeClassifier, plot_tree\nfrom sklearn.inspection import permutation_importance\n\n# Suppress all UserWarnings\nwarnings.filterwarnings(\"ignore\", category=UserWarning)\n```\n:::\n\n\n# Introduction\nThe goal of this task is to build several machine learning models for predicting the survival status of patients with liver cirrhosis. The dataset for model development and training is sourced from the [Cirrhosis Patient Survival Prediction](https://archive.ics.uci.edu/dataset/878/cirrhosis+patient+survival+prediction+dataset-1) dataset in the UC Irvine Machine Learning Repository. The data is licensed under CC BY, allowing it to be freely used for this exercise. This dataset contains 17 clinical features collected from 418 patients with liver cirrhosis. The survival states included are Death (0), Censored (1), and Censored due to liver transplant (2).\n\nSince there are three target classes, this is a multi-class classification problem. For the success measures, the following were used:\n\n  * Confusion Matrix to give a breakdown of actual vs. predicted classes.\n  * Precision, Recall, and F1-Score using macro averaging to treat all classes equally\n     - Precision: How many predicted class X are actually class X?\n     - Recall: How many actual class X were correctly predicted?\n     - F1-Score: Harmonic mean of precision and recall.\n\n# EDA\nHere, I conduct the exploratory data analysis. Starting by loading the data, then exploring the data using descriptive statistics and visualisations to understand features and target variables.\n\n::: {#bbccc2a9 .cell execution_count=2}\n``` {.python .cell-code}\n# Load data \ndf = pd.read_csv(\"cirrhosis.csv\")\n\n# Inspect the head of the data\nprint(df.head())\n\n# Inspect the shape of the data\nprint(f\"\\nData shape: {df.shape}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly Spiders  \\\n0   1     400      D  D-penicillamine  21464   F       Y            Y       Y   \n1   2    4500      C  D-penicillamine  20617   F       N            Y       Y   \n2   3    1012      D  D-penicillamine  25594   M       N            N       N   \n3   4    1925      D  D-penicillamine  19994   F       N            Y       Y   \n4   5    1504     CL          Placebo  13918   F       N            Y       Y   \n\n  Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \\\n0     Y       14.5        261.0     2.60   156.0    1718.0  137.95   \n1     N        1.1        302.0     4.14    54.0    7394.8  113.52   \n2     S        1.4        176.0     3.48   210.0     516.0   96.10   \n3     S        1.8        244.0     2.54    64.0    6121.8   60.63   \n4     N        3.4        279.0     3.53   143.0     671.0  113.15   \n\n   Tryglicerides  Platelets  Prothrombin  Stage  \n0          172.0      190.0         12.2    4.0  \n1           88.0      221.0         10.6    3.0  \n2           55.0      151.0         12.0    4.0  \n3           92.0      183.0         10.3    4.0  \n4           72.0      136.0         10.9    3.0  \n\nData shape: (418, 20)\n```\n:::\n:::\n\n\n### Drop irrelevant columns\nThe ID and N_Days columns are not clinical features as specified in the dataset metadata. This task involves only using the clinical features for model development.\n\n::: {#733287f8 .cell execution_count=3}\n``` {.python .cell-code}\ndf.drop([\"ID\", \"N_Days\"], axis=1, inplace=True)\n```\n:::\n\n\n## Check for missing values\nInspection for missing values reveals that some of the features are missing a significant number of entries. These will be handled in the pre-processing section. \n\n::: {#1d537198 .cell execution_count=4}\n``` {.python .cell-code}\n# Check how many null values are in the data frame\nprint(\"\\nFeature Name  Number of missing entries\")\nprint(df.isnull().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFeature Name  Number of missing entries\nStatus             0\nDrug             106\nAge                0\nSex                0\nAscites          106\nHepatomegaly     106\nSpiders          106\nEdema              0\nBilirubin          0\nCholesterol      134\nAlbumin            0\nCopper           108\nAlk_Phos         106\nSGOT             106\nTryglicerides    136\nPlatelets         11\nProthrombin        2\nStage              6\ndtype: int64\n```\n:::\n:::\n\n\n## Basis statistics\nInspect the statistics of the numerical features. A value of count below 418, signifies the feature has missing values. The maximum value \n\n::: {#ca7f429d .cell execution_count=5}\n``` {.python .cell-code}\ndf.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Age</th>\n      <th>Bilirubin</th>\n      <th>Cholesterol</th>\n      <th>Albumin</th>\n      <th>Copper</th>\n      <th>Alk_Phos</th>\n      <th>SGOT</th>\n      <th>Tryglicerides</th>\n      <th>Platelets</th>\n      <th>Prothrombin</th>\n      <th>Stage</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>418.000000</td>\n      <td>418.000000</td>\n      <td>284.000000</td>\n      <td>418.000000</td>\n      <td>310.000000</td>\n      <td>312.000000</td>\n      <td>312.000000</td>\n      <td>282.000000</td>\n      <td>407.000000</td>\n      <td>416.000000</td>\n      <td>412.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>18533.351675</td>\n      <td>3.220813</td>\n      <td>369.510563</td>\n      <td>3.497440</td>\n      <td>97.648387</td>\n      <td>1982.655769</td>\n      <td>122.556346</td>\n      <td>124.702128</td>\n      <td>257.024570</td>\n      <td>10.731731</td>\n      <td>3.024272</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>3815.845055</td>\n      <td>4.407506</td>\n      <td>231.944545</td>\n      <td>0.424972</td>\n      <td>85.613920</td>\n      <td>2140.388824</td>\n      <td>56.699525</td>\n      <td>65.148639</td>\n      <td>98.325585</td>\n      <td>1.022000</td>\n      <td>0.882042</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>9598.000000</td>\n      <td>0.300000</td>\n      <td>120.000000</td>\n      <td>1.960000</td>\n      <td>4.000000</td>\n      <td>289.000000</td>\n      <td>26.350000</td>\n      <td>33.000000</td>\n      <td>62.000000</td>\n      <td>9.000000</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>15644.500000</td>\n      <td>0.800000</td>\n      <td>249.500000</td>\n      <td>3.242500</td>\n      <td>41.250000</td>\n      <td>871.500000</td>\n      <td>80.600000</td>\n      <td>84.250000</td>\n      <td>188.500000</td>\n      <td>10.000000</td>\n      <td>2.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>18628.000000</td>\n      <td>1.400000</td>\n      <td>309.500000</td>\n      <td>3.530000</td>\n      <td>73.000000</td>\n      <td>1259.000000</td>\n      <td>114.700000</td>\n      <td>108.000000</td>\n      <td>251.000000</td>\n      <td>10.600000</td>\n      <td>3.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>21272.500000</td>\n      <td>3.400000</td>\n      <td>400.000000</td>\n      <td>3.770000</td>\n      <td>123.000000</td>\n      <td>1980.000000</td>\n      <td>151.900000</td>\n      <td>151.000000</td>\n      <td>318.000000</td>\n      <td>11.100000</td>\n      <td>4.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>28650.000000</td>\n      <td>28.000000</td>\n      <td>1775.000000</td>\n      <td>4.640000</td>\n      <td>588.000000</td>\n      <td>13862.400000</td>\n      <td>457.250000</td>\n      <td>598.000000</td>\n      <td>721.000000</td>\n      <td>18.000000</td>\n      <td>4.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Visualisations\n\n### Numerical features\nHistograms of each numerical feature are shown below. Apart from age, the other numerical features show skew (both positive and negative) and outliers.\n\n::: {#214ac062 .cell execution_count=6}\n``` {.python .cell-code}\n# Get a list of the numerical columns \nnum_cols = df.select_dtypes(include=[\"float64\", \"int64\"]).columns\n\ncustom_palette = [\n    \"skyblue\", \"salmon\", \"lightgreen\", \"orange\", \"violet\",\n    \"gold\", \"turquoise\", \"lightcoral\", \"plum\", \"khaki\", \"mediumseagreen\"\n]\n\n# Plot the numerical data\nfig, axes = plt.subplots(6, 2, figsize = (8, 16))\naxes = axes.flatten()\n\nfor i, col in enumerate(num_cols):\n    sns.histplot(data = df[col], kde = True, ax = axes[i], color=custom_palette[i])\n\n# Remove the unused subplot (12th axis)\nfor j in range(len(num_cols), len(axes)):\n    fig.delaxes(axes[j])\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-7-output-1.png){}\n:::\n:::\n\n\n::: {#aeea8321 .cell execution_count=7}\n``` {.python .cell-code}\nfig, axes = plt.subplots(6, 2, figsize = (8, 16))\naxes = axes.flatten()\n\nfor i, col in enumerate(num_cols):\n    sns.boxplot(data = df[col], ax = axes[i], color=custom_palette[i])\n\n# Remove the unused subplot (12th axis)\nfor j in range(len(num_cols), len(axes)):\n    fig.delaxes(axes[j])\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-8-output-1.png){}\n:::\n:::\n\n\n### Categorical features\nBar plots of each categorical feature are shown below. Some of the feature columns are quite imbalanced, such as Sex, Ascites, Edema, and stage. The target \"Status\" also exhibits an imbalance between the classes. \n\n::: {#ab9b8b86 .cell execution_count=8}\n``` {.python .cell-code}\n# Get a list of categorical columns\ncat_cols = df.select_dtypes(include=[\"object\"]).columns\n\nfig, axes = plt.subplots(4, 2, figsize = (8, 16))\naxes = axes.flatten()\n\n# Plot the categorical data\nfor i, col in enumerate(cat_cols):\n    sns.countplot(x=df[col], data=df, hue=df[col], ax=axes[i], legend=False)\n\n# Remove the unused subplot (12th axis)\nfor j in range(len(cat_cols), len(axes)):\n    fig.delaxes(axes[j])\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-9-output-1.png){}\n:::\n:::\n\n\n# Preprocess the data\n\n## Check and remove duplicates\n\n::: {#5ffd614e .cell execution_count=9}\n``` {.python .cell-code}\n# Count duplicate rows\nduplicate_count = df.duplicated().sum()\n\nprint(f\"Number of duplicate rows: {duplicate_count}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of duplicate rows: 0\n```\n:::\n:::\n\n\n## Handling missing values\nIn the EDA section, it was noted that many of the features had missing values. These occurred in both the numerical and categorical features. The imputation method used for each type is:\n  * Numerical: Use the median to avoid the effect of outliers.\n  * Categorical: Use the most common (mode).\n\n::: {#97e3176f .cell execution_count=10}\n``` {.python .cell-code}\n# Detect and analyse missing values\nmissing_count = df.isnull().sum().astype(int)\nmissing_percentage = round(df.isnull().mean() * 100, 2)\n\n# Create a DataFrame\nmissing_df = pd.DataFrame({\n    \"missing_count\": missing_count,\n    \"missing_percentage\": missing_percentage\n})\n                                                                      \n# Check the number of missing values for the numerical features\nprint(missing_df.loc[num_cols])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               missing_count  missing_percentage\nAge                        0                0.00\nBilirubin                  0                0.00\nCholesterol              134               32.06\nAlbumin                    0                0.00\nCopper                   108               25.84\nAlk_Phos                 106               25.36\nSGOT                     106               25.36\nTryglicerides            136               32.54\nPlatelets                 11                2.63\nProthrombin                2                0.48\nStage                      6                1.44\n```\n:::\n:::\n\n\n::: {#f93339dc .cell execution_count=11}\n``` {.python .cell-code}\n# Replacing missing values in numerical columns using the median \nfor col in num_cols:\n    df[col] = df[col].fillna(df[col].median())\n```\n:::\n\n\n::: {#204d30ef .cell execution_count=12}\n``` {.python .cell-code}\n# Check the number of missing values is now zero.\nprint(\"\\nFeature Name  Number of missing entries\")\nprint(df[num_cols].isnull().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFeature Name  Number of missing entries\nAge              0\nBilirubin        0\nCholesterol      0\nAlbumin          0\nCopper           0\nAlk_Phos         0\nSGOT             0\nTryglicerides    0\nPlatelets        0\nProthrombin      0\nStage            0\ndtype: int64\n```\n:::\n:::\n\n\n::: {#8d8f1378 .cell execution_count=13}\n``` {.python .cell-code}\n# Remove the \"Status\" from the list, as this is our target\ncat_cols = cat_cols[1:]\n\n# Check the number of missing values for the categorical features\nprint(missing_df.loc[cat_cols])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              missing_count  missing_percentage\nDrug                    106               25.36\nSex                       0                0.00\nAscites                 106               25.36\nHepatomegaly            106               25.36\nSpiders                 106               25.36\nEdema                     0                0.00\n```\n:::\n:::\n\n\n::: {#9be263f6 .cell execution_count=14}\n``` {.python .cell-code}\nfor col in cat_cols:\n    df[col] = df[col].fillna(df[col].mode().values[0])\n```\n:::\n\n\n::: {#4ba51911 .cell execution_count=15}\n``` {.python .cell-code}\n# Check the number of missing values is now zero.\nprint(\"\\nFeature Name  Number of missing entries\")\nprint(df[cat_cols].isnull().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFeature Name  Number of missing entries\nDrug            0\nSex             0\nAscites         0\nHepatomegaly    0\nSpiders         0\nEdema           0\ndtype: int64\n```\n:::\n:::\n\n\n## Split data into test and train\nStratified sampling has been used to ensure the class proportions remain the same in the test and train sets.\n\n### Create features and target\n\n::: {#dd8651b7 .cell execution_count=16}\n``` {.python .cell-code}\nX_df = df.drop([\"Status\"], axis=1)\ny_df = df[\"Status\"]\nprint(f\"Training shape: {X_df.shape}\")\nprint(f\"Target shape: {y_df.shape}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTraining shape: (418, 17)\nTarget shape: (418,)\n```\n:::\n:::\n\n\n### Split the data\n\n::: {#3ab13058 .cell execution_count=17}\n``` {.python .cell-code}\nstratSplit = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=0)\n\nfor train_index, test_index in stratSplit.split(X_df, y_df):\n    X_train_df = X_df.iloc[train_index]\n    X_test_df = X_df.iloc[test_index]\n    y_train_df = y_df.iloc[train_index]\n    y_test_df = y_df.iloc[test_index]\n\nX_train_df.reset_index(drop=True, inplace=True)\nX_test_df.reset_index(drop=True, inplace=True)\ny_train_df.reset_index(drop=True, inplace=True)\ny_test_df.reset_index(drop=True, inplace=True)\n```\n:::\n\n\n## Check data types\n\n::: {#725426f5 .cell execution_count=18}\n``` {.python .cell-code}\n# Numerical column types\nprint(f\"{len(num_cols)} columns of numerical type:\")\nX_train_df[num_cols].dtypes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n11 columns of numerical type:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=43}\n```\nAge                int64\nBilirubin        float64\nCholesterol      float64\nAlbumin          float64\nCopper           float64\nAlk_Phos         float64\nSGOT             float64\nTryglicerides    float64\nPlatelets        float64\nProthrombin      float64\nStage            float64\ndtype: object\n```\n:::\n:::\n\n\n::: {#8f3d44ef .cell execution_count=19}\n``` {.python .cell-code}\n# Categorical column types\nprint(f\"{len(cat_cols)} columns of type categorical\")\nX_train_df[cat_cols].dtypes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n6 columns of type categorical\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=44}\n```\nDrug            object\nSex             object\nAscites         object\nHepatomegaly    object\nSpiders         object\nEdema           object\ndtype: object\n```\n:::\n:::\n\n\n## Encode categorical features\nAll of the categorical features can be one-hot encoded.\n\n::: {#eb073df2 .cell execution_count=20}\n``` {.python .cell-code}\n# Print unique values for each selected column\nfor column in cat_cols:\n    unique_values = df[column].unique()\n    print(f\"Unique values in column '{column}':\")\n    print(unique_values)\n    print(\"-\" *70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUnique values in column 'Drug':\n['D-penicillamine' 'Placebo']\n----------------------------------------------------------------------\nUnique values in column 'Sex':\n['F' 'M']\n----------------------------------------------------------------------\nUnique values in column 'Ascites':\n['Y' 'N']\n----------------------------------------------------------------------\nUnique values in column 'Hepatomegaly':\n['Y' 'N']\n----------------------------------------------------------------------\nUnique values in column 'Spiders':\n['Y' 'N']\n----------------------------------------------------------------------\nUnique values in column 'Edema':\n['Y' 'N' 'S']\n----------------------------------------------------------------------\n```\n:::\n:::\n\n\n### Encoding nominal categorical features\n\n::: {#3e929819 .cell execution_count=21}\n``` {.python .cell-code}\n# Columns to encode\none_hot_cols = cat_cols[:]\n\n# OneHotEncoder setup\nencoder = OneHotEncoder(sparse_output=False)\nX_nom_enc_train = encoder.fit_transform(X_train_df[one_hot_cols])\nX_nom_enc_test = encoder.fit_transform(X_test_df[one_hot_cols])\n\n# Convert to DataFrame with column names\ntrain_enc_df = pd.DataFrame(X_nom_enc_train, columns=encoder.get_feature_names_out(one_hot_cols))\ntest_enc_df = pd.DataFrame(X_nom_enc_test, columns=encoder.get_feature_names_out(one_hot_cols))\n\n# Assemble training and test sets\nX_train_enc_df = pd.concat([train_enc_df , X_train_df[num_cols]], axis=1)\n#X_train_enc_df.info()\nX_test_enc_df = pd.concat([test_enc_df , X_test_df[num_cols]], axis=1)\nX_test_enc_df.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=46}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Drug_D-penicillamine</th>\n      <th>Drug_Placebo</th>\n      <th>Sex_F</th>\n      <th>Sex_M</th>\n      <th>Ascites_N</th>\n      <th>Ascites_Y</th>\n      <th>Hepatomegaly_N</th>\n      <th>Hepatomegaly_Y</th>\n      <th>Spiders_N</th>\n      <th>Spiders_Y</th>\n      <th>...</th>\n      <th>Bilirubin</th>\n      <th>Cholesterol</th>\n      <th>Albumin</th>\n      <th>Copper</th>\n      <th>Alk_Phos</th>\n      <th>SGOT</th>\n      <th>Tryglicerides</th>\n      <th>Platelets</th>\n      <th>Prothrombin</th>\n      <th>Stage</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>...</td>\n      <td>4.4</td>\n      <td>316.0</td>\n      <td>3.62</td>\n      <td>308.0</td>\n      <td>1119.0</td>\n      <td>114.70</td>\n      <td>322.0</td>\n      <td>282.0</td>\n      <td>9.8</td>\n      <td>4.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>...</td>\n      <td>1.5</td>\n      <td>293.0</td>\n      <td>4.30</td>\n      <td>50.0</td>\n      <td>975.0</td>\n      <td>125.55</td>\n      <td>56.0</td>\n      <td>336.0</td>\n      <td>9.1</td>\n      <td>2.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>...</td>\n      <td>7.3</td>\n      <td>309.5</td>\n      <td>3.52</td>\n      <td>73.0</td>\n      <td>1259.0</td>\n      <td>114.70</td>\n      <td>108.0</td>\n      <td>265.0</td>\n      <td>11.1</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>...</td>\n      <td>3.8</td>\n      <td>426.0</td>\n      <td>3.22</td>\n      <td>96.0</td>\n      <td>2716.0</td>\n      <td>210.80</td>\n      <td>113.0</td>\n      <td>228.0</td>\n      <td>10.6</td>\n      <td>2.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>...</td>\n      <td>1.8</td>\n      <td>244.0</td>\n      <td>2.54</td>\n      <td>64.0</td>\n      <td>6121.8</td>\n      <td>60.63</td>\n      <td>92.0</td>\n      <td>183.0</td>\n      <td>10.3</td>\n      <td>4.0</td>\n    </tr>\n  </tbody>\n</table>\n<p>5 rows × 24 columns</p>\n</div>\n```\n:::\n:::\n\n\n### Target encoding\n\n::: {#4ae6d484 .cell execution_count=22}\n``` {.python .cell-code}\nstatus_mapping = {\"D\": 0, \"C\": 1, \"CL\": 2}\n\n# Apply the mapping\ny_train_df = y_train_df.map(status_mapping)\ny_test_df = y_test_df.map(status_mapping)\n```\n:::\n\n\n## Feature scaling\n\n::: {#98e523bd .cell execution_count=23}\n``` {.python .cell-code}\n# Create numpy arrays using the encoded and values for the features.\nX_train_enc = X_train_enc_df.to_numpy()\nX_test_enc = X_test_enc_df.to_numpy()\n```\n:::\n\n\n::: {#2cc9ac9e .cell execution_count=24}\n``` {.python .cell-code}\n# Fit scaler on training data\nscaler = StandardScaler()\nX_train = scaler.fit_transform(X_train_enc)\n\n# Transform test data using the same scaler\nX_test = scaler.transform(X_test_enc)\n\npd.DataFrame(X_train).describe().round(3)\npd.DataFrame(X_test).describe().round(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=49}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n      <th>4</th>\n      <th>5</th>\n      <th>6</th>\n      <th>7</th>\n      <th>8</th>\n      <th>9</th>\n      <th>...</th>\n      <th>14</th>\n      <th>15</th>\n      <th>16</th>\n      <th>17</th>\n      <th>18</th>\n      <th>19</th>\n      <th>20</th>\n      <th>21</th>\n      <th>22</th>\n      <th>23</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>...</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n      <td>84.000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>0.212</td>\n      <td>-0.212</td>\n      <td>0.178</td>\n      <td>-0.178</td>\n      <td>-0.011</td>\n      <td>0.011</td>\n      <td>-0.109</td>\n      <td>0.109</td>\n      <td>-0.145</td>\n      <td>0.145</td>\n      <td>...</td>\n      <td>0.059</td>\n      <td>0.175</td>\n      <td>0.001</td>\n      <td>0.032</td>\n      <td>0.076</td>\n      <td>0.104</td>\n      <td>0.054</td>\n      <td>0.070</td>\n      <td>0.069</td>\n      <td>-0.281</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>0.932</td>\n      <td>0.932</td>\n      <td>0.741</td>\n      <td>0.741</td>\n      <td>1.028</td>\n      <td>1.028</td>\n      <td>0.971</td>\n      <td>0.971</td>\n      <td>1.098</td>\n      <td>1.098</td>\n      <td>...</td>\n      <td>1.132</td>\n      <td>1.502</td>\n      <td>1.029</td>\n      <td>0.928</td>\n      <td>0.950</td>\n      <td>0.855</td>\n      <td>1.162</td>\n      <td>0.962</td>\n      <td>1.162</td>\n      <td>1.126</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>-1.253</td>\n      <td>-0.798</td>\n      <td>-2.750</td>\n      <td>-0.364</td>\n      <td>-4.072</td>\n      <td>-0.246</td>\n      <td>-0.773</td>\n      <td>-1.293</td>\n      <td>-1.978</td>\n      <td>-0.506</td>\n      <td>...</td>\n      <td>-0.646</td>\n      <td>-1.231</td>\n      <td>-3.638</td>\n      <td>-1.070</td>\n      <td>-0.712</td>\n      <td>-1.510</td>\n      <td>-1.391</td>\n      <td>-1.837</td>\n      <td>-1.641</td>\n      <td>-2.443</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>-1.253</td>\n      <td>-0.798</td>\n      <td>0.364</td>\n      <td>-0.364</td>\n      <td>0.246</td>\n      <td>-0.246</td>\n      <td>-0.773</td>\n      <td>-1.293</td>\n      <td>-1.978</td>\n      <td>-0.506</td>\n      <td>...</td>\n      <td>-0.553</td>\n      <td>-0.243</td>\n      <td>-0.355</td>\n      <td>-0.438</td>\n      <td>-0.270</td>\n      <td>-0.226</td>\n      <td>-0.401</td>\n      <td>-0.629</td>\n      <td>-0.728</td>\n      <td>-1.264</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>0.798</td>\n      <td>-0.798</td>\n      <td>0.364</td>\n      <td>-0.364</td>\n      <td>0.246</td>\n      <td>-0.246</td>\n      <td>-0.773</td>\n      <td>0.773</td>\n      <td>0.506</td>\n      <td>-0.506</td>\n      <td>...</td>\n      <td>-0.354</td>\n      <td>-0.201</td>\n      <td>0.077</td>\n      <td>-0.236</td>\n      <td>-0.270</td>\n      <td>-0.095</td>\n      <td>-0.205</td>\n      <td>-0.046</td>\n      <td>-0.119</td>\n      <td>-0.085</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>0.798</td>\n      <td>1.253</td>\n      <td>0.364</td>\n      <td>-0.364</td>\n      <td>0.246</td>\n      <td>-0.246</td>\n      <td>1.293</td>\n      <td>0.773</td>\n      <td>0.506</td>\n      <td>1.978</td>\n      <td>...</td>\n      <td>0.129</td>\n      <td>0.063</td>\n      <td>0.740</td>\n      <td>0.089</td>\n      <td>0.042</td>\n      <td>0.348</td>\n      <td>0.173</td>\n      <td>0.627</td>\n      <td>0.312</td>\n      <td>1.094</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>0.798</td>\n      <td>1.253</td>\n      <td>0.364</td>\n      <td>2.750</td>\n      <td>0.246</td>\n      <td>4.072</td>\n      <td>1.293</td>\n      <td>0.773</td>\n      <td>0.506</td>\n      <td>1.978</td>\n      <td>...</td>\n      <td>5.208</td>\n      <td>8.300</td>\n      <td>2.420</td>\n      <td>4.677</td>\n      <td>5.168</td>\n      <td>4.148</td>\n      <td>5.996</td>\n      <td>2.687</td>\n      <td>6.476</td>\n      <td>1.094</td>\n    </tr>\n  </tbody>\n</table>\n<p>8 rows × 24 columns</p>\n</div>\n```\n:::\n:::\n\n\n## Training set class distribution\nHere, I inspect the balance of the classes in the training set. The figure below reveals that there is a slight imbalance between the \"D\" and \"C\" classes and a major imbalance between the \"D\",\"C\" and \"CL\" classes. \n\n::: {#36f4e6cc .cell execution_count=25}\n``` {.python .cell-code}\n# Count distribution of 0s, 1s and 2s\ntarget_counts = y_train_df.value_counts()\n\n# Plot the distribution\nplt.figure(figsize=(6, 4))\ntarget_counts.plot(kind=\"bar\", color=[\"red\", \"orange\", \"green\"])\nplt.title(\"Distribution of Target Classes in Training Set\")\nplt.xlabel(\"Target Class\")\nplt.ylabel(\"Count\")\nplt.xticks(ticks=[0, 1, 2], labels=[\"0 (D - Death)\", \"1 (C - Alive)\", \"2 (CL- Transplant)\" ], rotation=0)\nplt.tight_layout()\n\n# Save the figure\nplt.savefig(\"images/class_balance.png\")\n\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-26-output-1.png){}\n:::\n:::\n\n\n### Make Numpy arrays for target sets\n\n::: {#0264dbea .cell execution_count=26}\n``` {.python .cell-code}\ny_train = y_train_df.to_numpy()\ny_test = y_test_df.to_numpy()\n```\n:::\n\n\n# Models\nThree supervised learning models are created to predict the status classes. For each type of model, two models are created: the first for the original imbalanced training set and the second for a resampled training set designed to address the class imbalance in the dataset.\n\n## Model validation and over-/under-fitting assessment\nTo validate each model and assess whether it is over- or under-fitting, a five-fold cross-validation was used, and the output from the cross-validation was used to plot the learning curves.\n\nCross-validation was chosen for the following reasons:\n\n* Improves model performance estimation by using multiple data splits.\n* Helps detect over-fitting by testing on varied subsets of data.\n* Maximises use of limited data for both training and testing.\n* Enables fair model comparison under consistent evaluation conditions.\n\nLearning curves were used to interpret model performance because they:\n\n* Can be used to diagnose under-fitting or over-fitting by comparing training and validation performance.\n* Can guide model selection by comparing learning curves of different models to choose the best one.\n\nThe learning curve figures in this report show:\n\n* F1 Macro Score (y-axis) versus the training set size (x-axis).\n* Training score (red curve).\n* Cross-validation score (green curve)\n* Variability across folds (standard deviation) is shaded.\n\n::: {#34ae86fc .cell execution_count=27}\n``` {.python .cell-code}\ndef run_cross_validate(model, X_train, y_train, label):\n    \"\"\"\n    Function to perform cross-validation and plot learning curves\n\n    :param model: Model to validate.\n    :param X_train: Training data.\n    :param y_train: TRaining labels.\n    :returns: None\n    \"\"\"\n    # Define stratified k-fold cross-validation\n    cv = StratifiedKFold(n_splits=5)\n\n    # Generate learning curve data\n    train_sizes, train_scores, test_scores = learning_curve(\n        model, X_train, y_train, cv=cv, scoring=\"f1_macro\",\n        train_sizes=np.linspace(0.1, 1.0, 10), n_jobs=-1\n    )\n\n    # Calculate mean and standard deviation\n    train_scores_mean = np.mean(train_scores, axis=1)\n    test_scores_mean = np.mean(test_scores, axis=1)\n    train_scores_std = np.std(train_scores, axis=1)\n    test_scores_std = np.std(test_scores, axis=1)\n\n    # Plot the learning curve\n    plt.figure(figsize=(10, 6))\n    plt.title(f\"Learning Curve for {label}\")\n    plt.xlabel(\"Training Set Size\")\n    plt.ylabel(\"F1 Macro Score\")\n    plt.grid(True)\n\n    # Plot with shaded standard deviation\n    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,\n                     train_scores_mean + train_scores_std, alpha=0.1, color=\"r\")\n    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,\n                     test_scores_mean + test_scores_std, alpha=0.1, color=\"g\")\n\n    plt.plot(train_sizes, train_scores_mean, 'o-', color=\"r\", label=\"Training score\")\n    plt.plot(train_sizes, test_scores_mean, 'o-', color=\"g\", label=\"Cross-validation score\")\n\n    plt.legend(loc=\"best\")\n    plt.tight_layout()\n    \n    # Save the figure\n    plt.savefig(f\"images/{label}_learning_curve.png\")\n```\n:::\n\n\n## Dealing with imbalance\nTo address the class imbalance, the Synthetic Minority Over-sampling Technique (SMOTE) was utilised to create a resampled training set. SMOTE generates synthetic samples for minority classes by interpolating between existing samples. SMOTE preserves all original data and avoids over-fitting.\n\n::: {#3a1573dc .cell execution_count=28}\n``` {.python .cell-code}\n# Apply SMOTE to balance all classes to match the majority class (class 0)\nsmote = SMOTE(random_state=0)\nX_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)\n\n# Check new class distribution\nsmote_counts = pd.DataFrame(y_train_smote).value_counts()\n\n# Plot the distribution\nplt.figure(figsize=(6, 4))\nsmote_counts.plot(kind=\"bar\", color=[\"red\", \"orange\", \"green\"])\nplt.title(\"Distribution of Target Classes in Resampled Training Set\")\nplt.xlabel(\"Target Class\")\nplt.ylabel(\"Count\")\nplt.xticks(ticks=[0, 1, 2], labels=[\"0 (D - Death)\", \"1 (C - Alive)\", \"2 (CL- Transplant)\" ], rotation=0)\nplt.tight_layout()\n# Save the figure\nplt.savefig(\"images/resampled_class_balance.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-29-output-1.png){}\n:::\n:::\n\n\n## Model 1 - Logistic regression\nLogistic regression was chosen as one of the models because it is simple and interpretable.\n\nThe logistic regression model in scikit-learn has several hyperparameters. Hyperparameter optimisation was performed to find the combination of parameters that gives the best model performance. \n\nThe Logistic regression hyperparameters are:\n\n * Penalty: The regularisation method.\n * C: The regularisation strength. Higher values give less regularisation.\n * Solver: The type of solver used.\n * Maximum Iterations: Controls how long the solver runs.\n * Tolerance: Determines the stopping criteria for the optimisation.\n * Class Weight: Useful for imbalanced datasets.\n\nAs this is a multi-class problem, the only solver that can handle such problems and supports none, L1 and L2 regularisation is \"saga\". Therefore, the solver type was removed from the hyperparameter tuning.\n\nThe scikit-learn GridSearchCV is used to execute the parameter tuning. It runs through all combinations of the parameters and uses cross-validation to evaluate the model's performance. The macro version of the F1 score was used for the model evaluation during the grid search. F1 is the harmonic mean of precision and recall. The macro option calculates metrics for each class and finds their unweighted mean. The main objective of this work is to predict the \"Status\" of patients accurately. Therefore, the aim is to strike a balance between the recall and the precision. The number of folds in the cross-validation was chosen to be five to balance performance with confidence. More folds will give higher confidence in the result; However, this comes at an additional computational cost.\n\n::: {#e31a251c .cell execution_count=29}\n``` {.python .cell-code}\ndef run_grid_search_lr(X_train, y_train):\n    \"\"\"\n    Function to run a grid search for hyperparameter tuning of logistic regression models.\n\n    :param X_train: Feature training set\n    :param y_train: Label training set\n    :returns: GridSearchCV model\n    \"\"\"\n    # Initialise model\n    logreg_model = LogisticRegression(solver=\"saga\", random_state=0)\n\n    # Create parameter grid\n    param_grid = {\n        \"penalty\": [None, \"l1\", \"l2\"],\n        \"C\": [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0],\n        \"class_weight\": [None, \"balanced\"],\n        \"max_iter\": [100, 500, 1000],\n        \"tol\": [1e-5, 1e-4, 1e-3],\n    }\n\n    # Set up GridSearchCV\n    # GridSearchCV uses stratified sampling internally, so no special action is required.\n    # Interested in performance for all classes, so use the macro option\n    grid_search = GridSearchCV(logreg_model, param_grid, cv=5, scoring=\"f1_macro\", n_jobs=-1,\n                               return_train_score=True)\n\n    # Fit the model\n    grid_search.fit(X_train, y_train)\n\n    # Convert results to DataFrame\n    results_df = pd.DataFrame(grid_search.cv_results_)\n\n    # Create a readable label for each parameter combination\n    results_df[\"param_combo\"] = results_df.apply(\n        lambda row: f\"{row['param_penalty']}, C={row['param_C']}, iter={row['param_max_iter']}, tol={row['param_tol']}, weight={row['param_class_weight']}\",\n        axis=1\n    )\n\n    top_10 = results_df.sort_values(by=\"mean_test_score\", ascending=False).head(10)\n    print(\"Top 10 parameters combinations results\")\n    print(top_10[[\"param_combo\", \"mean_test_score\"]].to_string(index=False))\n\n    # Best parameters and score\n    print(\"\\nBest Parameters:\", grid_search.best_params_)\n    print(f\"Best Score: {grid_search.best_score_:.4f}\")\n\n    return grid_search\n```\n:::\n\n\n### Logistic regression hyperparameter tuning with original data\n\n::: {#5f4e784d .cell execution_count=30}\n``` {.python .cell-code}\n# Run GridSearch on original data\ngrid_original = run_grid_search_lr(X_train, y_train)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTop 10 parameters combinations results\n                                      param_combo  mean_test_score\n l2, C=0.1, iter=500, tol=0.0001, weight=balanced         0.574750\n  l2, C=0.1, iter=100, tol=1e-05, weight=balanced         0.574750\n l2, C=0.1, iter=100, tol=0.0001, weight=balanced         0.574750\n l2, C=0.1, iter=1000, tol=1e-05, weight=balanced         0.574750\nl2, C=0.1, iter=1000, tol=0.0001, weight=balanced         0.574750\n  l2, C=0.1, iter=500, tol=1e-05, weight=balanced         0.574750\n l2, C=0.1, iter=1000, tol=0.001, weight=balanced         0.574049\n  l2, C=0.1, iter=500, tol=0.001, weight=balanced         0.574049\n  l2, C=0.1, iter=100, tol=0.001, weight=balanced         0.574049\nl2, C=0.01, iter=100, tol=0.0001, weight=balanced         0.555429\n\nBest Parameters: {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 100, 'penalty': 'l2', 'tol': 1e-05}\nBest Score: 0.5748\n```\n:::\n:::\n\n\n### Train the model using the best parameters\n\n::: {#9863b2f2 .cell execution_count=31}\n``` {.python .cell-code}\nlogreg_bm = grid_original.best_estimator_\nlogreg_bm.fit(X_train, y_train)\n```\n\n::: {.cell-output .cell-output-display execution_count=56}\n```{=html}\n<style>#sk-container-id-1 {\n  /* Definition of color scheme common for light and dark mode */\n  --sklearn-color-text: #000;\n  --sklearn-color-text-muted: #666;\n  --sklearn-color-line: gray;\n  /* Definition of color scheme for unfitted estimators */\n  --sklearn-color-unfitted-level-0: #fff5e6;\n  --sklearn-color-unfitted-level-1: #f6e4d2;\n  --sklearn-color-unfitted-level-2: #ffe0b3;\n  --sklearn-color-unfitted-level-3: chocolate;\n  /* Definition of color scheme for fitted estimators */\n  --sklearn-color-fitted-level-0: #f0f8ff;\n  --sklearn-color-fitted-level-1: #d4ebff;\n  --sklearn-color-fitted-level-2: #b3dbfd;\n  --sklearn-color-fitted-level-3: cornflowerblue;\n\n  /* Specific color for light theme */\n  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-icon: #696969;\n\n  @media (prefers-color-scheme: dark) {\n    /* Redefinition of color scheme for dark theme */\n    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-icon: #878787;\n  }\n}\n\n#sk-container-id-1 {\n  color: var(--sklearn-color-text);\n}\n\n#sk-container-id-1 pre {\n  padding: 0;\n}\n\n#sk-container-id-1 input.sk-hidden--visually {\n  border: 0;\n  clip: rect(1px 1px 1px 1px);\n  clip: rect(1px, 1px, 1px, 1px);\n  height: 1px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: absolute;\n  width: 1px;\n}\n\n#sk-container-id-1 div.sk-dashed-wrapped {\n  border: 1px dashed var(--sklearn-color-line);\n  margin: 0 0.4em 0.5em 0.4em;\n  box-sizing: border-box;\n  padding-bottom: 0.4em;\n  background-color: var(--sklearn-color-background);\n}\n\n#sk-container-id-1 div.sk-container {\n  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n     but bootstrap.min.css set `[hidden] { display: none !important; }`\n     so we also need the `!important` here to be able to override the\n     default hidden behavior on the sphinx rendered scikit-learn.org.\n     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n  display: inline-block !important;\n  position: relative;\n}\n\n#sk-container-id-1 div.sk-text-repr-fallback {\n  display: none;\n}\n\ndiv.sk-parallel-item,\ndiv.sk-serial,\ndiv.sk-item {\n  /* draw centered vertical line to link estimators */\n  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n  background-size: 2px 100%;\n  background-repeat: no-repeat;\n  background-position: center center;\n}\n\n/* Parallel-specific style estimator block */\n\n#sk-container-id-1 div.sk-parallel-item::after {\n  content: \"\";\n  width: 100%;\n  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n  flex-grow: 1;\n}\n\n#sk-container-id-1 div.sk-parallel {\n  display: flex;\n  align-items: stretch;\n  justify-content: center;\n  background-color: var(--sklearn-color-background);\n  position: relative;\n}\n\n#sk-container-id-1 div.sk-parallel-item {\n  display: flex;\n  flex-direction: column;\n}\n\n#sk-container-id-1 div.sk-parallel-item:first-child::after {\n  align-self: flex-end;\n  width: 50%;\n}\n\n#sk-container-id-1 div.sk-parallel-item:last-child::after {\n  align-self: flex-start;\n  width: 50%;\n}\n\n#sk-container-id-1 div.sk-parallel-item:only-child::after {\n  width: 0;\n}\n\n/* Serial-specific style estimator block */\n\n#sk-container-id-1 div.sk-serial {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  background-color: var(--sklearn-color-background);\n  padding-right: 1em;\n  padding-left: 1em;\n}\n\n\n/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\nclickable and can be expanded/collapsed.\n- Pipeline and ColumnTransformer use this feature and define the default style\n- Estimators will overwrite some part of the style using the `sk-estimator` class\n*/\n\n/* Pipeline and ColumnTransformer style (default) */\n\n#sk-container-id-1 div.sk-toggleable {\n  /* Default theme specific background. It is overwritten whether we have a\n  specific estimator or a Pipeline/ColumnTransformer */\n  background-color: var(--sklearn-color-background);\n}\n\n/* Toggleable label */\n#sk-container-id-1 label.sk-toggleable__label {\n  cursor: pointer;\n  display: flex;\n  width: 100%;\n  margin-bottom: 0;\n  padding: 0.5em;\n  box-sizing: border-box;\n  text-align: center;\n  align-items: start;\n  justify-content: space-between;\n  gap: 0.5em;\n}\n\n#sk-container-id-1 label.sk-toggleable__label .caption {\n  font-size: 0.6rem;\n  font-weight: lighter;\n  color: var(--sklearn-color-text-muted);\n}\n\n#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n  /* Arrow on the left of the label */\n  content: \"▸\";\n  float: left;\n  margin-right: 0.25em;\n  color: var(--sklearn-color-icon);\n}\n\n#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n  color: var(--sklearn-color-text);\n}\n\n/* Toggleable content - dropdown */\n\n#sk-container-id-1 div.sk-toggleable__content {\n  display: none;\n  text-align: left;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-1 div.sk-toggleable__content.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-1 div.sk-toggleable__content pre {\n  margin: 0.2em;\n  border-radius: 0.25em;\n  color: var(--sklearn-color-text);\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n  /* unfitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n  /* Expand drop-down */\n  display: block;\n  width: 100%;\n  overflow: visible;\n}\n\n#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n  content: \"▾\";\n}\n\n/* Pipeline/ColumnTransformer-specific style */\n\n#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator-specific style */\n\n/* Colorize estimator box */\n#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n#sk-container-id-1 div.sk-label label {\n  /* The background is the default theme color */\n  color: var(--sklearn-color-text-on-default-background);\n}\n\n/* On hover, darken the color of the background */\n#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n/* Label box, darken color on hover, fitted */\n#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator label */\n\n#sk-container-id-1 div.sk-label label {\n  font-family: monospace;\n  font-weight: bold;\n  display: inline-block;\n  line-height: 1.2em;\n}\n\n#sk-container-id-1 div.sk-label-container {\n  text-align: center;\n}\n\n/* Estimator-specific */\n#sk-container-id-1 div.sk-estimator {\n  font-family: monospace;\n  border: 1px dotted var(--sklearn-color-border-box);\n  border-radius: 0.25em;\n  box-sizing: border-box;\n  margin-bottom: 0.5em;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-1 div.sk-estimator.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n/* on hover */\n#sk-container-id-1 div.sk-estimator:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-1 div.sk-estimator.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Specification for estimator info (e.g. \"i\" and \"?\") */\n\n/* Common style for \"i\" and \"?\" */\n\n.sk-estimator-doc-link,\na:link.sk-estimator-doc-link,\na:visited.sk-estimator-doc-link {\n  float: right;\n  font-size: smaller;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1em;\n  height: 1em;\n  width: 1em;\n  text-decoration: none !important;\n  margin-left: 0.5em;\n  text-align: center;\n  /* unfitted */\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n  color: var(--sklearn-color-unfitted-level-1);\n}\n\n.sk-estimator-doc-link.fitted,\na:link.sk-estimator-doc-link.fitted,\na:visited.sk-estimator-doc-link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\ndiv.sk-estimator:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\ndiv.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n/* Span, style for the box shown on hovering the info icon */\n.sk-estimator-doc-link span {\n  display: none;\n  z-index: 9999;\n  position: relative;\n  font-weight: normal;\n  right: .2ex;\n  padding: .5ex;\n  margin: .5ex;\n  width: min-content;\n  min-width: 20ex;\n  max-width: 50ex;\n  color: var(--sklearn-color-text);\n  box-shadow: 2pt 2pt 4pt #999;\n  /* unfitted */\n  background: var(--sklearn-color-unfitted-level-0);\n  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n}\n\n.sk-estimator-doc-link.fitted span {\n  /* fitted */\n  background: var(--sklearn-color-fitted-level-0);\n  border: var(--sklearn-color-fitted-level-3);\n}\n\n.sk-estimator-doc-link:hover span {\n  display: block;\n}\n\n/* \"?\"-specific style due to the `<a>` HTML tag */\n\n#sk-container-id-1 a.estimator_doc_link {\n  float: right;\n  font-size: 1rem;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1rem;\n  height: 1rem;\n  width: 1rem;\n  text-decoration: none;\n  /* unfitted */\n  color: var(--sklearn-color-unfitted-level-1);\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n}\n\n#sk-container-id-1 a.estimator_doc_link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\n#sk-container-id-1 a.estimator_doc_link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n}\n\n.estimator-table summary {\n    padding: .5rem;\n    font-family: monospace;\n    cursor: pointer;\n}\n\n.estimator-table details[open] {\n    padding-left: 0.1rem;\n    padding-right: 0.1rem;\n    padding-bottom: 0.3rem;\n}\n\n.estimator-table .parameters-table {\n    margin-left: auto !important;\n    margin-right: auto !important;\n}\n\n.estimator-table .parameters-table tr:nth-child(odd) {\n    background-color: #fff;\n}\n\n.estimator-table .parameters-table tr:nth-child(even) {\n    background-color: #f6f6f6;\n}\n\n.estimator-table .parameters-table tr:hover {\n    background-color: #e0e0e0;\n}\n\n.estimator-table table td {\n    border: 1px solid rgba(106, 105, 104, 0.232);\n}\n\n.user-set td {\n    color:rgb(255, 94, 0);\n    text-align: left;\n}\n\n.user-set td.value pre {\n    color:rgb(255, 94, 0) !important;\n    background-color: transparent !important;\n}\n\n.default td {\n    color: black;\n    text-align: left;\n}\n\n.user-set td i,\n.default td i {\n    color: black;\n}\n\n.copy-paste-icon {\n    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n    background-repeat: no-repeat;\n    background-size: 14px 14px;\n    background-position: 0;\n    display: inline-block;\n    width: 14px;\n    height: 14px;\n    cursor: pointer;\n}\n</style><body><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LogisticRegression(C=0.1, class_weight=&#x27;balanced&#x27;, random_state=0,\n                   solver=&#x27;saga&#x27;, tol=1e-05)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LogisticRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.linear_model.LogisticRegression.html\">?<span>Documentation for LogisticRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('penalty',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">penalty&nbsp;</td>\n            <td class=\"value\">&#x27;l2&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('dual',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">dual&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('tol',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">tol&nbsp;</td>\n            <td class=\"value\">1e-05</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('C',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">C&nbsp;</td>\n            <td class=\"value\">0.1</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('fit_intercept',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">fit_intercept&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('intercept_scaling',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">intercept_scaling&nbsp;</td>\n            <td class=\"value\">1</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('class_weight',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">class_weight&nbsp;</td>\n            <td class=\"value\">&#x27;balanced&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('random_state',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">random_state&nbsp;</td>\n            <td class=\"value\">0</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('solver',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">solver&nbsp;</td>\n            <td class=\"value\">&#x27;saga&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_iter',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_iter&nbsp;</td>\n            <td class=\"value\">100</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('multi_class',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">multi_class&nbsp;</td>\n            <td class=\"value\">&#x27;deprecated&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('verbose',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">verbose&nbsp;</td>\n            <td class=\"value\">0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('warm_start',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">warm_start&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('n_jobs',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">n_jobs&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('l1_ratio',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">l1_ratio&nbsp;</td>\n            <td class=\"value\">None</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n    // Get the parameter prefix from the closest toggleable content\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n\n    const originalStyle = element.style;\n    const computedStyle = window.getComputedStyle(element);\n    const originalWidth = computedStyle.width;\n    const originalHTML = element.innerHTML.replace('Copied!', '');\n\n    navigator.clipboard.writeText(fullParamName)\n        .then(() => {\n            element.style.width = originalWidth;\n            element.style.color = 'green';\n            element.innerHTML = \"Copied!\";\n\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        })\n        .catch(err => {\n            console.error('Failed to copy:', err);\n            element.style.color = 'red';\n            element.innerHTML = \"Failed!\";\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        });\n    return false;\n}\n\ndocument.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n\n    element.setAttribute('title', fullParamName);\n});\n</script></body>\n```\n:::\n:::\n\n\n::: {#740e2273 .cell execution_count=32}\n``` {.python .cell-code}\nrun_cross_validate(logreg_bm, X_train, y_train, \"Logistic Regression (original data)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-33-output-1.png){}\n:::\n:::\n\n\nInterpretation:\n\n *  As the model sees more data, it becomes less tailored to the small initial training set and generalises more, resulting in a drop in the training score. The drop suggests the model is no longer over-fitting to small samples.\n *  The cross-validation score increases, then stabilises as training size grows beyond 100. The model is learning and generalising better.\n *  The training and test curves become parallel, suggesting the model is not over-fitting.\n *  The low value for the score for both the training and validation curves indicates the model is under-fitting.\n *  The variation across folds suggests the model's performance across folds is consistent, indicating stability and reliability.\n\n### Logistic model - SMOTE resampled data\nSince the resampled training dataset is different, there is no guarantee that the previously identified hyperparameters will still be optimal for this dataset. Therefore, the grid search was repeated to find the combination of parameters that gave the best performance for the resampled training data.\n\n::: {#c58d6b6b .cell execution_count=33}\n``` {.python .cell-code}\n# Run GridSearch on SMOTE-balanced data\ngrid_smote = run_grid_search_lr(X_train_smote, y_train_smote)\nlogreg_bm_smote = grid_smote.best_estimator_\n\nrun_cross_validate(logreg_bm_smote, X_train_smote, y_train_smote, \"Logistic Regression (SMOTE resampled data)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTop 10 parameters combinations results\n                                      param_combo  mean_test_score\n  l2, C=0.1, iter=500, tol=0.001, weight=balanced         0.704506\n l2, C=0.1, iter=1000, tol=0.001, weight=balanced         0.704506\n      l2, C=0.1, iter=100, tol=0.001, weight=None         0.704506\n      l2, C=0.1, iter=500, tol=0.001, weight=None         0.704506\n     l2, C=0.1, iter=1000, tol=0.001, weight=None         0.704506\n  l2, C=0.1, iter=100, tol=0.001, weight=balanced         0.704506\n l2, C=0.1, iter=500, tol=0.0001, weight=balanced         0.702595\n l2, C=0.1, iter=1000, tol=1e-05, weight=balanced         0.702595\nl2, C=0.1, iter=1000, tol=0.0001, weight=balanced         0.702595\n  l2, C=0.1, iter=500, tol=1e-05, weight=balanced         0.702595\n\nBest Parameters: {'C': 0.1, 'class_weight': None, 'max_iter': 100, 'penalty': 'l2', 'tol': 0.001}\nBest Score: 0.7045\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-34-output-2.png){}\n:::\n:::\n\n\nInterpretation:\n  * Training score starts high (~0.6) and remains relatively stable, ending around ~0.7. Indicates the model fits the training data well, even with small datasets.\n  * Cross-validation score starts low (~0.35) and steadily improves with more training data, reaching ~0.72. Suggests the model generalises better as it sees more data.\n  * Large gap between training curves at small training sizes, implying overfitting. The model performs well on training data but poorly on unseen data.\n  * The gap narrows with more data, indicating improved generalisation and reduced overfitting.\n  * At low sample numbers, the variance across folds is high. This narrows as more training data is added.\n\n::: {#e2cb2b4e .cell execution_count=34}\n``` {.python .cell-code}\n# Report results\nprint(\"Original Data Performance:\")\nprint(\"Best Parameters:\", grid_original.best_params_)\nprint(\"\\nSMOTE-Balanced Data Performance:\")\nprint(\"Best Parameters:\", grid_smote.best_params_)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOriginal Data Performance:\nBest Parameters: {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 100, 'penalty': 'l2', 'tol': 1e-05}\n\nSMOTE-Balanced Data Performance:\nBest Parameters: {'C': 0.1, 'class_weight': None, 'max_iter': 100, 'penalty': 'l2', 'tol': 0.001}\n```\n:::\n:::\n\n\n## Model 2 - SVC\nSVC was chosen as one of the models because it is effective in high-dimensional spaces and works well with small datasets. \n\nThe SVC model in scikit-learn has several hyperparameters, and hyperparameter optimisation was performed to find the combination of parameters that gives the best model performance. \n\n**The SVC hyperparameters are**:\n\n  * Kernel: Options are \"linear\", \"RBF\", \"poly\" and \"sigmoid\".\n  * C: Regularisation parameter. Controls the trade-off between accuracy and generalisation. Available for all kernels.\n     - High values create tighter decision boundaries (risk of overfitting).  \n     - Low values allow smoother decision boundaries (risk of underfitting).\n  * Class Weight: Useful for imbalanced datasets.\n\n**Kernel-specific hyperparameters**:\n\n  * \"gamma\": Influence of individual data points. Available in \"RBF\", \"poly\", and \"sigmoid\".\n     - Higher values make the model focus on local structures (risk of overfitting).\n     - Lower values create smoother decision boundaries.\n  * \"coef0\": Controls curve shift in polynomial/sigmoid kernels.\n     - Impacts feature interactions.\n  * \"degree\": Defines the complexity of polynomial curves.\n     - Higher degrees create more flexible decision boundaries.\n\nAs there are a large number of possible combinations of hyperparameters. BayesSearchCV was used to explore the hyperparameter search space, as it is more efficient than a brute-force grid search. Again, a five-fold cross-validation with the macro version of the F1 score is used for model evaluation during the search.\n\n::: {#3a11f018 .cell execution_count=35}\n``` {.python .cell-code}\ndef run_search_svm(X_train, y_train):\n    \"\"\"\n    Function to run a Bayes search for hyperparameter tuning of SVM models.\n\n    :param X_train: Feature training set\n    :param y_train: Label training set\n    :returns: BayesSearchCV model\n    \"\"\"    \n    search_space = {\n        \"kernel\": [\"linear\", \"rbf\", \"poly\", \"sigmoid\"],\n        \"C\": (1e-3, 1e3, 'log-uniform'),\n        \"class_weight\": [None, \"balanced\"],\n        \"gamma\": (1e-4, 1, 'log-uniform'),\n        \"degree\": (2, 5),\n        \"coef0\": (-1, 1)\n    }\n\n    opt = BayesSearchCV(\n        SVC(probability=False, max_iter = -1, tol = 1e-3, verbose=True, random_state=0),\n        search_spaces=search_space,\n        scoring=\"f1_macro\", \n        cv=StratifiedKFold(n_splits=5),\n        n_iter=50,  # Number of iterations\n        n_jobs=-1,  # Use all cores\n        verbose=0,\n        random_state=0\n    )\n\n    opt.fit(X_train, y_train)  \n\n    # Convert results to DataFrame\n    results_df = pd.DataFrame(opt.cv_results_)\n\n    # Create a readable label for each parameter combination\n    results_df[\"param_combo\"] = results_df.apply(\n        lambda row: f\"{row['param_kernel']}, C={row['param_C']:.4f}, \"\n                    f\"weight={row['param_class_weight']}, gamma={row['param_gamma']:.4f},\"\n                    f\"degree={row['param_degree']}, coef0={row['param_coef0']},\",\n        axis=1\n    )\n\n    top_10 = results_df.sort_values(by=\"mean_test_score\", ascending=False).head(10)\n    print(\"\\nTop 10 parameters combinations results\")\n    print(top_10[[\"param_combo\", \"mean_test_score\"]].to_string(index=False))\n\n    print(\"Best parameters:\", opt.best_params_)\n    print(\"Best score:\", opt.best_score_)\n\n    return opt\n```\n:::\n\n\n### SVC hyperparameter tuning with original data\n\n::: {#c766d83f .cell execution_count=36}\n``` {.python .cell-code}\n# Run GridSearch on original data\ngrid_original_svm = run_search_svm(X_train, y_train)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[LibSVM]\nTop 10 parameters combinations results\n                                                           param_combo  mean_test_score\n    linear, C=0.0407, weight=balanced, gamma=0.0005,degree=4, coef0=0,         0.578629\n   linear, C=0.0395, weight=balanced, gamma=0.0001,degree=3, coef0=-1,         0.575117\n   linear, C=0.0387, weight=balanced, gamma=0.0001,degree=2, coef0=-1,         0.575117\n    linear, C=0.0368, weight=balanced, gamma=0.0001,degree=2, coef0=0,         0.574452\n   linear, C=0.0563, weight=balanced, gamma=0.0004,degree=2, coef0=-1,         0.572485\n    linear, C=0.0355, weight=balanced, gamma=0.0011,degree=4, coef0=1,         0.571958\n   linear, C=0.0224, weight=balanced, gamma=0.0004,degree=4, coef0=-1,         0.567018\n   linear, C=0.0701, weight=balanced, gamma=0.0010,degree=4, coef0=-1,         0.562934\n    linear, C=0.0797, weight=balanced, gamma=0.0002,degree=5, coef0=0,         0.562934\nsigmoid, C=392.2376, weight=balanced, gamma=0.0001,degree=2, coef0=-1,         0.553314\nBest parameters: OrderedDict([('C', 0.04069971836887072), ('class_weight', 'balanced'), ('coef0', 0), ('degree', 4), ('gamma', 0.00047722740319078804), ('kernel', 'linear')])\nBest score: 0.5786290642921209\n```\n:::\n:::\n\n\n::: {#bdf69842 .cell execution_count=37}\n``` {.python .cell-code}\nsvm_bm = grid_original_svm.best_estimator_\nsvm_bm.fit(X_train, y_train)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[LibSVM]\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=62}\n```{=html}\n<style>#sk-container-id-2 {\n  /* Definition of color scheme common for light and dark mode */\n  --sklearn-color-text: #000;\n  --sklearn-color-text-muted: #666;\n  --sklearn-color-line: gray;\n  /* Definition of color scheme for unfitted estimators */\n  --sklearn-color-unfitted-level-0: #fff5e6;\n  --sklearn-color-unfitted-level-1: #f6e4d2;\n  --sklearn-color-unfitted-level-2: #ffe0b3;\n  --sklearn-color-unfitted-level-3: chocolate;\n  /* Definition of color scheme for fitted estimators */\n  --sklearn-color-fitted-level-0: #f0f8ff;\n  --sklearn-color-fitted-level-1: #d4ebff;\n  --sklearn-color-fitted-level-2: #b3dbfd;\n  --sklearn-color-fitted-level-3: cornflowerblue;\n\n  /* Specific color for light theme */\n  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n  --sklearn-color-icon: #696969;\n\n  @media (prefers-color-scheme: dark) {\n    /* Redefinition of color scheme for dark theme */\n    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n    --sklearn-color-icon: #878787;\n  }\n}\n\n#sk-container-id-2 {\n  color: var(--sklearn-color-text);\n}\n\n#sk-container-id-2 pre {\n  padding: 0;\n}\n\n#sk-container-id-2 input.sk-hidden--visually {\n  border: 0;\n  clip: rect(1px 1px 1px 1px);\n  clip: rect(1px, 1px, 1px, 1px);\n  height: 1px;\n  margin: -1px;\n  overflow: hidden;\n  padding: 0;\n  position: absolute;\n  width: 1px;\n}\n\n#sk-container-id-2 div.sk-dashed-wrapped {\n  border: 1px dashed var(--sklearn-color-line);\n  margin: 0 0.4em 0.5em 0.4em;\n  box-sizing: border-box;\n  padding-bottom: 0.4em;\n  background-color: var(--sklearn-color-background);\n}\n\n#sk-container-id-2 div.sk-container {\n  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n     but bootstrap.min.css set `[hidden] { display: none !important; }`\n     so we also need the `!important` here to be able to override the\n     default hidden behavior on the sphinx rendered scikit-learn.org.\n     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n  display: inline-block !important;\n  position: relative;\n}\n\n#sk-container-id-2 div.sk-text-repr-fallback {\n  display: none;\n}\n\ndiv.sk-parallel-item,\ndiv.sk-serial,\ndiv.sk-item {\n  /* draw centered vertical line to link estimators */\n  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n  background-size: 2px 100%;\n  background-repeat: no-repeat;\n  background-position: center center;\n}\n\n/* Parallel-specific style estimator block */\n\n#sk-container-id-2 div.sk-parallel-item::after {\n  content: \"\";\n  width: 100%;\n  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n  flex-grow: 1;\n}\n\n#sk-container-id-2 div.sk-parallel {\n  display: flex;\n  align-items: stretch;\n  justify-content: center;\n  background-color: var(--sklearn-color-background);\n  position: relative;\n}\n\n#sk-container-id-2 div.sk-parallel-item {\n  display: flex;\n  flex-direction: column;\n}\n\n#sk-container-id-2 div.sk-parallel-item:first-child::after {\n  align-self: flex-end;\n  width: 50%;\n}\n\n#sk-container-id-2 div.sk-parallel-item:last-child::after {\n  align-self: flex-start;\n  width: 50%;\n}\n\n#sk-container-id-2 div.sk-parallel-item:only-child::after {\n  width: 0;\n}\n\n/* Serial-specific style estimator block */\n\n#sk-container-id-2 div.sk-serial {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  background-color: var(--sklearn-color-background);\n  padding-right: 1em;\n  padding-left: 1em;\n}\n\n\n/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\nclickable and can be expanded/collapsed.\n- Pipeline and ColumnTransformer use this feature and define the default style\n- Estimators will overwrite some part of the style using the `sk-estimator` class\n*/\n\n/* Pipeline and ColumnTransformer style (default) */\n\n#sk-container-id-2 div.sk-toggleable {\n  /* Default theme specific background. It is overwritten whether we have a\n  specific estimator or a Pipeline/ColumnTransformer */\n  background-color: var(--sklearn-color-background);\n}\n\n/* Toggleable label */\n#sk-container-id-2 label.sk-toggleable__label {\n  cursor: pointer;\n  display: flex;\n  width: 100%;\n  margin-bottom: 0;\n  padding: 0.5em;\n  box-sizing: border-box;\n  text-align: center;\n  align-items: start;\n  justify-content: space-between;\n  gap: 0.5em;\n}\n\n#sk-container-id-2 label.sk-toggleable__label .caption {\n  font-size: 0.6rem;\n  font-weight: lighter;\n  color: var(--sklearn-color-text-muted);\n}\n\n#sk-container-id-2 label.sk-toggleable__label-arrow:before {\n  /* Arrow on the left of the label */\n  content: \"▸\";\n  float: left;\n  margin-right: 0.25em;\n  color: var(--sklearn-color-icon);\n}\n\n#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {\n  color: var(--sklearn-color-text);\n}\n\n/* Toggleable content - dropdown */\n\n#sk-container-id-2 div.sk-toggleable__content {\n  display: none;\n  text-align: left;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-2 div.sk-toggleable__content.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-2 div.sk-toggleable__content pre {\n  margin: 0.2em;\n  border-radius: 0.25em;\n  color: var(--sklearn-color-text);\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-2 div.sk-toggleable__content.fitted pre {\n  /* unfitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n  /* Expand drop-down */\n  display: block;\n  width: 100%;\n  overflow: visible;\n}\n\n#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n  content: \"▾\";\n}\n\n/* Pipeline/ColumnTransformer-specific style */\n\n#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-2 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator-specific style */\n\n/* Colorize estimator box */\n#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-2 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n#sk-container-id-2 div.sk-label label.sk-toggleable__label,\n#sk-container-id-2 div.sk-label label {\n  /* The background is the default theme color */\n  color: var(--sklearn-color-text-on-default-background);\n}\n\n/* On hover, darken the color of the background */\n#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n/* Label box, darken color on hover, fitted */\n#sk-container-id-2 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n  color: var(--sklearn-color-text);\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Estimator label */\n\n#sk-container-id-2 div.sk-label label {\n  font-family: monospace;\n  font-weight: bold;\n  display: inline-block;\n  line-height: 1.2em;\n}\n\n#sk-container-id-2 div.sk-label-container {\n  text-align: center;\n}\n\n/* Estimator-specific */\n#sk-container-id-2 div.sk-estimator {\n  font-family: monospace;\n  border: 1px dotted var(--sklearn-color-border-box);\n  border-radius: 0.25em;\n  box-sizing: border-box;\n  margin-bottom: 0.5em;\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-0);\n}\n\n#sk-container-id-2 div.sk-estimator.fitted {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-0);\n}\n\n/* on hover */\n#sk-container-id-2 div.sk-estimator:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-2);\n}\n\n#sk-container-id-2 div.sk-estimator.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-2);\n}\n\n/* Specification for estimator info (e.g. \"i\" and \"?\") */\n\n/* Common style for \"i\" and \"?\" */\n\n.sk-estimator-doc-link,\na:link.sk-estimator-doc-link,\na:visited.sk-estimator-doc-link {\n  float: right;\n  font-size: smaller;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1em;\n  height: 1em;\n  width: 1em;\n  text-decoration: none !important;\n  margin-left: 0.5em;\n  text-align: center;\n  /* unfitted */\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n  color: var(--sklearn-color-unfitted-level-1);\n}\n\n.sk-estimator-doc-link.fitted,\na:link.sk-estimator-doc-link.fitted,\na:visited.sk-estimator-doc-link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\ndiv.sk-estimator:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link:hover,\n.sk-estimator-doc-link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\ndiv.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover,\ndiv.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n.sk-estimator-doc-link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n/* Span, style for the box shown on hovering the info icon */\n.sk-estimator-doc-link span {\n  display: none;\n  z-index: 9999;\n  position: relative;\n  font-weight: normal;\n  right: .2ex;\n  padding: .5ex;\n  margin: .5ex;\n  width: min-content;\n  min-width: 20ex;\n  max-width: 50ex;\n  color: var(--sklearn-color-text);\n  box-shadow: 2pt 2pt 4pt #999;\n  /* unfitted */\n  background: var(--sklearn-color-unfitted-level-0);\n  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n}\n\n.sk-estimator-doc-link.fitted span {\n  /* fitted */\n  background: var(--sklearn-color-fitted-level-0);\n  border: var(--sklearn-color-fitted-level-3);\n}\n\n.sk-estimator-doc-link:hover span {\n  display: block;\n}\n\n/* \"?\"-specific style due to the `<a>` HTML tag */\n\n#sk-container-id-2 a.estimator_doc_link {\n  float: right;\n  font-size: 1rem;\n  line-height: 1em;\n  font-family: monospace;\n  background-color: var(--sklearn-color-background);\n  border-radius: 1rem;\n  height: 1rem;\n  width: 1rem;\n  text-decoration: none;\n  /* unfitted */\n  color: var(--sklearn-color-unfitted-level-1);\n  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n}\n\n#sk-container-id-2 a.estimator_doc_link.fitted {\n  /* fitted */\n  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n  color: var(--sklearn-color-fitted-level-1);\n}\n\n/* On hover */\n#sk-container-id-2 a.estimator_doc_link:hover {\n  /* unfitted */\n  background-color: var(--sklearn-color-unfitted-level-3);\n  color: var(--sklearn-color-background);\n  text-decoration: none;\n}\n\n#sk-container-id-2 a.estimator_doc_link.fitted:hover {\n  /* fitted */\n  background-color: var(--sklearn-color-fitted-level-3);\n}\n\n.estimator-table summary {\n    padding: .5rem;\n    font-family: monospace;\n    cursor: pointer;\n}\n\n.estimator-table details[open] {\n    padding-left: 0.1rem;\n    padding-right: 0.1rem;\n    padding-bottom: 0.3rem;\n}\n\n.estimator-table .parameters-table {\n    margin-left: auto !important;\n    margin-right: auto !important;\n}\n\n.estimator-table .parameters-table tr:nth-child(odd) {\n    background-color: #fff;\n}\n\n.estimator-table .parameters-table tr:nth-child(even) {\n    background-color: #f6f6f6;\n}\n\n.estimator-table .parameters-table tr:hover {\n    background-color: #e0e0e0;\n}\n\n.estimator-table table td {\n    border: 1px solid rgba(106, 105, 104, 0.232);\n}\n\n.user-set td {\n    color:rgb(255, 94, 0);\n    text-align: left;\n}\n\n.user-set td.value pre {\n    color:rgb(255, 94, 0) !important;\n    background-color: transparent !important;\n}\n\n.default td {\n    color: black;\n    text-align: left;\n}\n\n.user-set td i,\n.default td i {\n    color: black;\n}\n\n.copy-paste-icon {\n    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n    background-repeat: no-repeat;\n    background-size: 14px 14px;\n    background-position: 0;\n    display: inline-block;\n    width: 14px;\n    height: 14px;\n    cursor: pointer;\n}\n</style><body><div id=\"sk-container-id-2\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>SVC(C=0.04069971836887072, class_weight=&#x27;balanced&#x27;, coef0=0, degree=4,\n    gamma=0.00047722740319078804, kernel=&#x27;linear&#x27;, random_state=0,\n    verbose=True)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-2\" type=\"checkbox\" checked><label for=\"sk-estimator-id-2\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>SVC</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.svm.SVC.html\">?<span>Documentation for SVC</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n        <div class=\"estimator-table\">\n            <details>\n                <summary>Parameters</summary>\n                <table class=\"parameters-table\">\n                  <tbody>\n                    \n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('C',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">C&nbsp;</td>\n            <td class=\"value\">0.04069971836887072</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('kernel',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">kernel&nbsp;</td>\n            <td class=\"value\">&#x27;linear&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('degree',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">degree&nbsp;</td>\n            <td class=\"value\">4</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('gamma',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">gamma&nbsp;</td>\n            <td class=\"value\">0.00047722740319078804</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('coef0',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">coef0&nbsp;</td>\n            <td class=\"value\">0</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('shrinking',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">shrinking&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('probability',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">probability&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('tol',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">tol&nbsp;</td>\n            <td class=\"value\">0.001</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('cache_size',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">cache_size&nbsp;</td>\n            <td class=\"value\">200</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('class_weight',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">class_weight&nbsp;</td>\n            <td class=\"value\">&#x27;balanced&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('verbose',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">verbose&nbsp;</td>\n            <td class=\"value\">True</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('max_iter',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">max_iter&nbsp;</td>\n            <td class=\"value\">-1</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('decision_function_shape',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">decision_function_shape&nbsp;</td>\n            <td class=\"value\">&#x27;ovr&#x27;</td>\n        </tr>\n    \n\n        <tr class=\"default\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('break_ties',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">break_ties&nbsp;</td>\n            <td class=\"value\">False</td>\n        </tr>\n    \n\n        <tr class=\"user-set\">\n            <td><i class=\"copy-paste-icon\"\n                 onclick=\"copyToClipboard('random_state',\n                          this.parentElement.nextElementSibling)\"\n            ></i></td>\n            <td class=\"param\">random_state&nbsp;</td>\n            <td class=\"value\">0</td>\n        </tr>\n    \n                  </tbody>\n                </table>\n            </details>\n        </div>\n    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n    // Get the parameter prefix from the closest toggleable content\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n\n    const originalStyle = element.style;\n    const computedStyle = window.getComputedStyle(element);\n    const originalWidth = computedStyle.width;\n    const originalHTML = element.innerHTML.replace('Copied!', '');\n\n    navigator.clipboard.writeText(fullParamName)\n        .then(() => {\n            element.style.width = originalWidth;\n            element.style.color = 'green';\n            element.innerHTML = \"Copied!\";\n\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        })\n        .catch(err => {\n            console.error('Failed to copy:', err);\n            element.style.color = 'red';\n            element.innerHTML = \"Failed!\";\n            setTimeout(() => {\n                element.innerHTML = originalHTML;\n                element.style = originalStyle;\n            }, 2000);\n        });\n    return false;\n}\n\ndocument.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n    const toggleableContent = element.closest('.sk-toggleable__content');\n    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n\n    element.setAttribute('title', fullParamName);\n});\n</script></body>\n```\n:::\n:::\n\n\n### Model validation and over-/under-fitting assessment\n\n::: {#6414cd2b .cell execution_count=38}\n``` {.python .cell-code}\nrun_cross_validate(svm_bm, X_train, y_train, \"SVC (original data)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-39-output-1.png){}\n:::\n:::\n\n\nInterpretation:\n\n  * Training score starts high (~0.82) with small data, then decreases and stabilises around 0.61. Indicates the model initially over-fits but generalises better with more data.\n  * Cross-validation score starts low (~0.42) and steadily improves with more training data, reaching ~0.58. Suggests the model generalises better as it sees more data.\n  * Large gap between training curves at small training sizes, implying over-fitting. The model performs well on training data but poorly on unseen data.\n  * The gap narrows with more data, indicating improved generalisation and reduced over-fitting.\n  * The low value for the score for both the training and validation curves indicates the model is under-fitting.      \n  * At low sample numbers, the variance across folds is high, narrowing as more training data is added.\n\n### SVC model - SMOTE resampled data\n\n::: {#9da94467 .cell execution_count=39}\n``` {.python .cell-code}\n# Run GridSearch on SMOTE-balanced data\ngrid_svm_smote = run_search_svm(X_train_smote, y_train_smote)\nsvm_bm_smote = grid_svm_smote.best_estimator_\n\nrun_cross_validate(svm_bm_smote, X_train_smote, y_train_smote, \"SVC (SMOTE resampled data)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[LibSVM]\nTop 10 parameters combinations results\n                                                        param_combo  mean_test_score\n     rbf, C=1000.0000, weight=None, gamma=0.0178,degree=5, coef0=1,         0.820066\n     rbf, C=1000.0000, weight=None, gamma=0.1240,degree=5, coef0=1,         0.818908\n rbf, C=458.5276, weight=balanced, gamma=0.0258,degree=5, coef0=-1,         0.811727\n rbf, C=1000.0000, weight=balanced, gamma=0.0223,degree=5, coef0=1,         0.808890\n    rbf, C=1000.0000, weight=None, gamma=0.0220,degree=5, coef0=-1,         0.806786\n     rbf, C=1000.0000, weight=None, gamma=0.0046,degree=5, coef0=1,         0.800797\n rbf, C=1000.0000, weight=balanced, gamma=0.0445,degree=2, coef0=1,         0.800797\n     rbf, C=1000.0000, weight=None, gamma=0.0257,degree=5, coef0=1,         0.799462\npoly, C=1000.0000, weight=balanced, gamma=0.0498,degree=5, coef0=1,         0.791560\n     rbf, C=1000.0000, weight=None, gamma=0.0295,degree=5, coef0=1,         0.790761\nBest parameters: OrderedDict([('C', 1000.0), ('class_weight', None), ('coef0', 1), ('degree', 5), ('gamma', 0.017811344333727035), ('kernel', 'rbf')])\nBest score: 0.8200656061445114\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-40-output-2.png){}\n:::\n:::\n\n\nInterpretation:\n\n  * Training score starts at 1.0, dips slightly and then ends near 1.0. The model is over-fitting the training data. Possibly due to the high C value.\n  * Cross-validation score starts low (~0.38) and steadily improves with more training data, reaching ~0.82. Suggests the model generalises better as it sees more data.\n  * Large gap between training curves at small training sizes, implying over-fitting. The model performs well on training data but poorly on unseen data.\n  * The gap narrows with more data, indicating improved generalisation and reduced over-fitting.     \n  * At low sample numbers, the variance across folds is high, narrowing as more training data is added.\n\n## Model 3 - Decision Tree\nA decision tree was chosen as one of the models because it is interpretable and handles non-linear relationships. The Decision Tree classifier in scikit-learn has many hyperparameters, mainly focused on early stopping of tree growth (pre-pruning). Whilst a Bayes or grid search could be used to find the optimal values for each of these hyperparameters, those approaches still require selecting an appropriate search space. An alternative approach to pre-pruning (pruning during growth) is post-pruning. In post-pruning, a full tree is grown and then pruned to remove branches that do not improve the performance. This approach is well-suited to small datasets, such as in this study and is the approach used. \n\n### Training an unpruned tree\n\n::: {#af5f59ce .cell execution_count=40}\n``` {.python .cell-code}\n# Train an unpruned decision tree\nunpruned_tree = DecisionTreeClassifier(random_state=0)\nunpruned_tree.fit(X_train, y_train)\n\n# Plot the decision tree\nplt.figure(figsize=(12, 8))\nplot_tree(unpruned_tree, filled=True, feature_names=X_train_enc_df.columns, class_names=[\"D\", \"C\", \"CL\" ])\nplt.title(\"Decision Tree Trained on original dataset\")\nplt.savefig(\"images/full_tree.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-41-output-1.png){}\n:::\n:::\n\n\n::: {#c26b9ab2 .cell execution_count=41}\n``` {.python .cell-code}\nrun_cross_validate(unpruned_tree, X_train, y_train, \"Decision Tree (unpruned original data)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-42-output-1.png){}\n:::\n:::\n\n\n### Tree pruning\nHere, the unpruned tree is used to obtain the cost-complexity path values. Then, using the cost complexity values, many trees are built, each with a different cost complexity value. A 5-fold stratified cross-validation is used to assess the macro F1 score for each of the pruned trees. The pruned tree that gives the highest mean cross-validation macro F1 score is chosen as the best tree.\n\n::: {#5837b985 .cell execution_count=42}\n``` {.python .cell-code}\ndef tree_pruning(full_tree, X_train, y_train, label):\n    \n    # Get cost-complexity pruning path\n    path = full_tree.cost_complexity_pruning_path(X_train, y_train)\n    ccp_alphas = path.ccp_alphas\n\n    # Train trees with different ccp_alpha values (no pre-pruning settings)\n    trees = []\n    for alpha in ccp_alphas:\n        clf = DecisionTreeClassifier(random_state=0, ccp_alpha=alpha)\n        clf.fit(X_train, y_train)\n        trees.append(clf)\n\n    # Define stratified k-fold cross-validation\n    cv = StratifiedKFold(n_splits=5)\n    \n    # Evaluate each tree using cross-validation\n    cv_scores = []\n    for clf in trees:\n        scores = cross_val_score(clf, X_train, y_train, cv=cv, scoring=\"f1_macro\")\n        cv_scores.append(np.mean(scores))\n\n    # Find the best pruned tree\n    best_index = np.argmax(cv_scores)\n    best_pruned_tree = trees[best_index]\n    best_alpha = ccp_alphas[best_index]\n    best_score = cv_scores[best_index]\n\n    # Print the best alpha and corresponding score\n    print(f\"Best ccp_alpha: {best_alpha:.4f}\")\n    print(f\"Best cross-validation accuracy: {best_score:.4f}\")\n\n    # Plot accuracy vs ccp_alpha\n    plt.figure(figsize=(10, 6))\n    plt.plot(ccp_alphas, cv_scores, marker='o', drawstyle=\"steps-post\")\n    plt.xlabel(\"ccp_alpha\")\n    plt.ylabel(\"Macro F1-score\")\n    plt.title(f\"F1-score vs CCP Alpha for Pruned Decision Trees {label}\")\n    plt.grid(True)\n    plt.tight_layout()\n    plt.savefig(f\"images/pruning_accuracy_comparison{label}.png\")\n\n    return best_pruned_tree\n```\n:::\n\n\n::: {#6f07534e .cell execution_count=43}\n``` {.python .cell-code}\nbest_pruned_tree = tree_pruning(unpruned_tree, X_train, y_train, label=\"(original data)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBest ccp_alpha: 0.0095\nBest cross-validation accuracy: 0.6100\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-44-output-2.png){}\n:::\n:::\n\n\n### Model evaluation: original data, best pruning\n\n::: {#0d5163ac .cell execution_count=44}\n``` {.python .cell-code}\nrun_cross_validate(best_pruned_tree, X_train, y_train, \"Decision Tree (best pruned, original data)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-45-output-1.png){}\n:::\n:::\n\n\nInterpretation:\n\n  * Training score starts at 1, indicating over-fitting on small datasets. As the training set size increases, the score drops and stabilises around 0.7, showing the model generalises better for larger training set sizes. \n  * Cross-validation score starts low (~0.45) and gradually increases reaching ~0.6. Suggests the model generalises better as it sees more data, but performance is low.\n  * Large gap between training curves at small training sizes, implying over-fitting. The model performs well on training data but poorly on unseen data. The gap narrows with more data, indicating improved generalisation and reduced over-fitting.     \n  * At low sample numbers, the variance across folds is low for the training and moderate for the validation. As more training data is added, the variation across folds increases for the training set and decreases slightly for the validation.\n\n::: {#8f0fc3e3 .cell execution_count=45}\n``` {.python .cell-code}\n# Plot the best decision tree\nplt.figure(figsize=(12, 8))\nplot_tree(best_pruned_tree, filled=True, feature_names=X_train_enc_df.columns, class_names=[\"D\", \"C\", \"CL\" ])\nplt.title(\"Best Pruned Decision Tree Trained on original dataset\")\nplt.savefig(\"best_decision_tree_origdata.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-46-output-1.png){}\n:::\n:::\n\n\n### Training an unpruned tree using resampled data\n\n::: {#71b44556 .cell execution_count=46}\n``` {.python .cell-code}\n# Train an unpruned decision tree\nunpruned_tree_sm = DecisionTreeClassifier(random_state=0)\nunpruned_tree_sm.fit(X_train_smote, y_train_smote)\n\n# Plot the decision tree\nplt.figure(figsize=(12, 8))\nplot_tree(unpruned_tree_sm, filled=True, feature_names=X_train_enc_df.columns, class_names=[\"D\", \"C\", \"CL\" ])\nplt.title(\"Decision Tree Trained on resampled dataset\")\nplt.savefig(\"images/full_tree_smote.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-47-output-1.png){}\n:::\n:::\n\n\n### Tree pruning: resampled data\n\n::: {#0838a20c .cell execution_count=47}\n``` {.python .cell-code}\nbest_pruned_tree_smote = tree_pruning(unpruned_tree_sm, X_train_smote, y_train_smote, label=\"(resampled data)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBest ccp_alpha: 0.0056\nBest cross-validation accuracy: 0.7422\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-48-output-2.png){}\n:::\n:::\n\n\n### Model evaluation: resampled data, best pruning\n\n::: {#6ae5e389 .cell execution_count=48}\n``` {.python .cell-code}\nrun_cross_validate(best_pruned_tree_smote, X_train_smote, y_train_smote, \"Decision Tree (best pruned, resampled data)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-49-output-1.png){}\n:::\n:::\n\n\nInterpretation:\n  * Training score starts at 1, indicating over-fitting on small datasets. As the training set size increases, the score drops slightly but remains high, indicating the model continues to fit the training data well. \n  * Cross-validation score starts low (~0.33) and gradually increases reaching ~0.75. Suggests the model generalises better as it sees more data, and the performance is higher.\n  * Large gap between training curves at small training sizes, implying over-fitting. The model performs well on training data but poorly on unseen data. The gap narrows with more data, indicating improved generalisation and reduced over-fitting.     \n  * The training curve shows low variation across folds. The validation curve shows moderate variation, especially at smaller training sizes. This variation decreases as the training size increases, indicating a more stable performance on unseen data.\n\n::: {#9063b0e8 .cell execution_count=49}\n``` {.python .cell-code}\n# Plot the best decision tree\nplt.figure(figsize=(12, 8))\nplot_tree(best_pruned_tree_smote, filled=True, feature_names=X_train_enc_df.columns, class_names=[\"D\", \"C\", \"CL\" ])\nplt.title(\"Best Pruned Decision Tree Trained on resampled dataset\")\nplt.savefig(\"best_decision_tree_resampleddata.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-50-output-1.png){}\n:::\n:::\n\n\n## Recommended model\nAccording to the reported results above, all three models using the original training data exhibited under-fitting. Using the resampled data, the SVC model showed signs of over-fitting. Both the logistic regression and decision tree models demonstrate a balance between over- and under-fitting. While the decision tree model shows a higher macro F1 score (0.7422) compared to the logistic regression (0.7045), the logistic regression model has a much lower variation in the validation score, indicating it is more stable across folds and the gap between the training and validation error was smallest. Therefore, the logistic regression model trained on the resampled data is recommended.\n\n# Prediction\nThe figure below displays the confusion matrix for the recommended logistic regression model evaluated using the test set. The model performs reasonably well in predicting deaths (D) and alive (C) cases. It struggles most with transplant (CL) cases, especially confusing them with alive (C).\n\n**Correct Predictions**\n- 22 deaths correctly predicted as deaths.\n- 22 alive correctly predicted as alive.\n- 3 transplants were correctly predicted as transplants.\n\n**Misclassifications**\n- 7 deaths predicted as alive, 3 as transplant.\n- 8 alive predicted as death, 17 as transplant.\n- 2 transplants predicted as death.\n\n::: {#3dd70e17 .cell execution_count=50}\n``` {.python .cell-code}\n# Predict on test set\ny_pred = logreg_bm_smote.predict(X_test)\n\nprint(classification_report(y_test, y_pred, target_names=[\"D\", \"C\", \"CL\"], digits=4))\n\n# Plot Confusion Matrix\nclasses = [\"D - Death\", \"C - Alive\", \"CL- Transplant\" ]\ncm = confusion_matrix(y_test, y_pred, labels=[0,1,2])\nplt.figure(figsize=(6, 5))\nsns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\", xticklabels=classes, yticklabels=classes)\nplt.xlabel(\"Predicted Labels\")\nplt.ylabel(\"Actual Labels\")\nplt.title(f\"Logistic Regression Confusion Matrix\")\nplt.savefig(\"images/lr_confusion.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              precision    recall  f1-score   support\n\n           D     0.7097    0.6875    0.6984        32\n           C     0.7500    0.4468    0.5600        47\n          CL     0.1200    0.6000    0.2000         5\n\n    accuracy                         0.5476        84\n   macro avg     0.5266    0.5781    0.4861        84\nweighted avg     0.6971    0.5476    0.5913        84\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-51-output-2.png){}\n:::\n:::\n\n\n# Feature importance\nTwo methods were used to analyse feature importance:\n\n* Permutation importance - evaluates how much a model's performance decreases when a feature's values are randomly shuffled. If shuffling a feature significantly worsens the model's performance, that feature is considered important.\n* SHAP analysis - ensures robust statistical inference by examining feature contributions at both individual and aggregate levels, while accounting for potential non-linear effects and class-specific patterns in the data.\n\n::: {#db7655b4 .cell execution_count=51}\n``` {.python .cell-code}\n# Permutation importance\nresult = permutation_importance(logreg_bm_smote, X_test, y_test, n_repeats=100, random_state=0, scoring=\"f1_macro\")\n\n# Create DataFrame for visualization\nimportance_df = pd.DataFrame({\n    \"Feature\": X_train_enc_df.columns,\n    \"Importance Mean\": result.importances_mean,\n    \"Importance Std\": result.importances_std\n}).sort_values(by=\"Importance Mean\", ascending=True)\n\n# Plot permutation importance\nplt.figure(figsize=(10, 8))\nplt.barh(importance_df[\"Feature\"], importance_df[\"Importance Mean\"], xerr=importance_df[\"Importance Std\"])\nplt.xlabel(\"Mean Importance\")\nplt.title(\"Permutation Feature Importance\")\nplt.tight_layout()\nplt.savefig(\"images/permutation_importance.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-52-output-1.png){}\n:::\n:::\n\n\nThe bar length shows the mean importance values. Positive values indicate that these features contribute positively to the model’s predictive power. Negative values suggest that shuffling the feature actually improved model performance, implying it may be noise or negatively correlated with the target. The error bars represent the standard deviation from multiple permutations. Wide error bars crossing zero imply low confidence in the feature's importance.\n\n## Permutation importance summary\n**Most Important features**\n\n  - Bilirubin and Age are the most statistically significant predictors — high mean importance.\n\n**Moderate Important features**\n\n  - SGOT, Copper, Stage, Prothrombin, Albumin, and Drug are also moderate predictors.\n\n**Less important**\n\n  - Ascite, Edema_N, Sex, Hepatomegaly and Tryglicerides are not important.\n  - Edema_Y/S, Spiders, Platelets and Cholesterol may be redundant - negative importance.\n\n::: {#c3234e63 .cell execution_count=52}\n``` {.python .cell-code}\nexplainer = shap.Explainer(logreg_bm_smote, X_test)\nshap_values = explainer(X_test)\n\n# Summary plot\nplt.figure()\nshap.summary_plot(shap_values, X_test, feature_names= X_train_enc_df.columns, max_display=24, show=False)\nplt.savefig(\"images/shap_summary_plot.png\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](Task6_2_files/figure-html/cell-53-output-1.png){}\n:::\n:::\n\n\nThe bar length represents the average magnitude of the SHAP values for each feature across all samples. A higher value means the feature has a greater impact on the model's predictions. Each colour corresponds to a class in the classification problem, showing how each feature contributes to different classes.\n\n## SHAP analysis summary\n\n**Most Important features**\n\n   - Age, Bilirubin: Their high SHAP values suggest they consistently influence the model’s output across samples.\n\n**Moderate Important features**\n\n   - Platelets, Prothrombin, Alk_Phos, Stage, Hepatomegaly, and Copper: Their moderate SHAP values suggest they consistently influence the model’s output across samples.\n\n**Less important**\n\n   - Sex, Edema, Spiders and Drug. Their low SHAP values suggest they consistently do not influence the model’s output across samples.\n     \n**Class-Specific Contributions:**\n\n   - Age is most influential in predicting Class 2 and 0.\n   - Bilirubin is the most influential in predicting Classes 1.\n\n## SHAP vs. Permutation Importance\n\n**Most Important Features (Both Methods Agree)**\n\n- Bilirubin: Top-ranked in both SHAP and permutation importance — strong indicator of liver function.\n- Age: Highly ranked in both — likely reflects disease progression or risk stratification.\n\n**Moderately Important Features**\n\n- Albumin, Alk_Phos, SGOT, Stage, Prothrombin, Platelets: These appear in both plots with moderate importance, suggesting consistent influence across methods.\n\n**Least Important Features (Both Methods Agree)**\n\n- Sex, Edema, Spiders\n\n**Discrepancies**\n\n- Drug: More prominent in permutation importance than SHAP.\n- Hepatomegaly: More prominent in SHAP than permutation importance. \n- Cholesterol: Ranked lowest in permutation importance (even negative), but has some presence in SHAP — possibly due to interaction effects captured by SHAP but not permutation.\n\n",
    "supporting": [
      "Task6_2_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}